// Code generated by ent, DO NOT EDIT.

package syspackage

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/saas-zero/saas-zero-basedata/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedID applies equality check predicate on the "created_id" field. It's identical to CreatedIDEQ.
func CreatedID(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedID applies equality check predicate on the "updated_id" field. It's identical to UpdatedIDEQ.
func UpdatedID(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldUpdatedID, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedID applies equality check predicate on the "deleted_id" field. It's identical to DeletedIDEQ.
func DeletedID(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldDeletedID, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldDeletedBy, v))
}

// Sort applies equality check predicate on the "sort" field. It's identical to SortEQ.
func Sort(v uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldSort, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldRemark, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldName, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedIDEQ applies the EQ predicate on the "created_id" field.
func CreatedIDEQ(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedIDNEQ applies the NEQ predicate on the "created_id" field.
func CreatedIDNEQ(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldCreatedID, v))
}

// CreatedIDIn applies the In predicate on the "created_id" field.
func CreatedIDIn(vs ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldCreatedID, vs...))
}

// CreatedIDNotIn applies the NotIn predicate on the "created_id" field.
func CreatedIDNotIn(vs ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldCreatedID, vs...))
}

// CreatedIDGT applies the GT predicate on the "created_id" field.
func CreatedIDGT(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldCreatedID, v))
}

// CreatedIDGTE applies the GTE predicate on the "created_id" field.
func CreatedIDGTE(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldCreatedID, v))
}

// CreatedIDLT applies the LT predicate on the "created_id" field.
func CreatedIDLT(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldCreatedID, v))
}

// CreatedIDLTE applies the LTE predicate on the "created_id" field.
func CreatedIDLTE(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldCreatedID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedIDEQ applies the EQ predicate on the "updated_id" field.
func UpdatedIDEQ(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldUpdatedID, v))
}

// UpdatedIDNEQ applies the NEQ predicate on the "updated_id" field.
func UpdatedIDNEQ(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldUpdatedID, v))
}

// UpdatedIDIn applies the In predicate on the "updated_id" field.
func UpdatedIDIn(vs ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldUpdatedID, vs...))
}

// UpdatedIDNotIn applies the NotIn predicate on the "updated_id" field.
func UpdatedIDNotIn(vs ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldUpdatedID, vs...))
}

// UpdatedIDGT applies the GT predicate on the "updated_id" field.
func UpdatedIDGT(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldUpdatedID, v))
}

// UpdatedIDGTE applies the GTE predicate on the "updated_id" field.
func UpdatedIDGTE(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldUpdatedID, v))
}

// UpdatedIDLT applies the LT predicate on the "updated_id" field.
func UpdatedIDLT(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldUpdatedID, v))
}

// UpdatedIDLTE applies the LTE predicate on the "updated_id" field.
func UpdatedIDLTE(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldUpdatedID, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedIDEQ applies the EQ predicate on the "deleted_id" field.
func DeletedIDEQ(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldDeletedID, v))
}

// DeletedIDNEQ applies the NEQ predicate on the "deleted_id" field.
func DeletedIDNEQ(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldDeletedID, v))
}

// DeletedIDIn applies the In predicate on the "deleted_id" field.
func DeletedIDIn(vs ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldDeletedID, vs...))
}

// DeletedIDNotIn applies the NotIn predicate on the "deleted_id" field.
func DeletedIDNotIn(vs ...int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldDeletedID, vs...))
}

// DeletedIDGT applies the GT predicate on the "deleted_id" field.
func DeletedIDGT(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldDeletedID, v))
}

// DeletedIDGTE applies the GTE predicate on the "deleted_id" field.
func DeletedIDGTE(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldDeletedID, v))
}

// DeletedIDLT applies the LT predicate on the "deleted_id" field.
func DeletedIDLT(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldDeletedID, v))
}

// DeletedIDLTE applies the LTE predicate on the "deleted_id" field.
func DeletedIDLTE(v int64) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldDeletedID, v))
}

// DeletedIDIsNil applies the IsNil predicate on the "deleted_id" field.
func DeletedIDIsNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIsNull(FieldDeletedID))
}

// DeletedIDNotNil applies the NotNil predicate on the "deleted_id" field.
func DeletedIDNotNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotNull(FieldDeletedID))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContainsFold(FieldDeletedBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldStatus, vs...))
}

// SortEQ applies the EQ predicate on the "sort" field.
func SortEQ(v uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldSort, v))
}

// SortNEQ applies the NEQ predicate on the "sort" field.
func SortNEQ(v uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldSort, v))
}

// SortIn applies the In predicate on the "sort" field.
func SortIn(vs ...uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldSort, vs...))
}

// SortNotIn applies the NotIn predicate on the "sort" field.
func SortNotIn(vs ...uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldSort, vs...))
}

// SortGT applies the GT predicate on the "sort" field.
func SortGT(v uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldSort, v))
}

// SortGTE applies the GTE predicate on the "sort" field.
func SortGTE(v uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldSort, v))
}

// SortLT applies the LT predicate on the "sort" field.
func SortLT(v uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldSort, v))
}

// SortLTE applies the LTE predicate on the "sort" field.
func SortLTE(v uint32) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldSort, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContainsFold(FieldRemark, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContainsFold(FieldName, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.SysPackage {
	return predicate.SysPackage(sql.FieldContainsFold(FieldCode, v))
}

// HasMenus applies the HasEdge predicate on the "menus" edge.
func HasMenus() predicate.SysPackage {
	return predicate.SysPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, MenusTable, MenusPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMenusWith applies the HasEdge predicate on the "menus" edge with a given conditions (other predicates).
func HasMenusWith(preds ...predicate.SysMenu) predicate.SysPackage {
	return predicate.SysPackage(func(s *sql.Selector) {
		step := newMenusStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApis applies the HasEdge predicate on the "apis" edge.
func HasApis() predicate.SysPackage {
	return predicate.SysPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ApisTable, ApisPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApisWith applies the HasEdge predicate on the "apis" edge with a given conditions (other predicates).
func HasApisWith(preds ...predicate.SysApi) predicate.SysPackage {
	return predicate.SysPackage(func(s *sql.Selector) {
		step := newApisStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTenants applies the HasEdge predicate on the "tenants" edge.
func HasTenants() predicate.SysPackage {
	return predicate.SysPackage(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TenantsTable, TenantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantsWith applies the HasEdge predicate on the "tenants" edge with a given conditions (other predicates).
func HasTenantsWith(preds ...predicate.SysTenant) predicate.SysPackage {
	return predicate.SysPackage(func(s *sql.Selector) {
		step := newTenantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysPackage) predicate.SysPackage {
	return predicate.SysPackage(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysPackage) predicate.SysPackage {
	return predicate.SysPackage(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysPackage) predicate.SysPackage {
	return predicate.SysPackage(sql.NotPredicates(p))
}
