// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package syspackages

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResp       = apps.EmptyResp
	IdReq           = apps.IdReq
	IdsReq          = apps.IdsReq
	PackageListResp = apps.PackageListResp
	PackagePageReq  = apps.PackagePageReq
	PackageReq      = apps.PackageReq
	PackageResp     = apps.PackageResp

	SysPackages interface {
		CreatePackage(ctx context.Context, in *PackageReq, opts ...grpc.CallOption) (*PackageResp, error)
		UpdatePackage(ctx context.Context, in *PackageReq, opts ...grpc.CallOption) (*PackageResp, error)
		DeletePackage(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error)
		GetPackageList(ctx context.Context, in *PackagePageReq, opts ...grpc.CallOption) (*PackageListResp, error)
		GetPackageById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*PackageResp, error)
	}

	defaultSysPackages struct {
		cli zrpc.Client
	}
)

func NewSysPackages(cli zrpc.Client) SysPackages {
	return &defaultSysPackages{
		cli: cli,
	}
}

func (m *defaultSysPackages) CreatePackage(ctx context.Context, in *PackageReq, opts ...grpc.CallOption) (*PackageResp, error) {
	client := apps.NewSysPackagesClient(m.cli.Conn())
	return client.CreatePackage(ctx, in, opts...)
}

func (m *defaultSysPackages) UpdatePackage(ctx context.Context, in *PackageReq, opts ...grpc.CallOption) (*PackageResp, error) {
	client := apps.NewSysPackagesClient(m.cli.Conn())
	return client.UpdatePackage(ctx, in, opts...)
}

func (m *defaultSysPackages) DeletePackage(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := apps.NewSysPackagesClient(m.cli.Conn())
	return client.DeletePackage(ctx, in, opts...)
}

func (m *defaultSysPackages) GetPackageList(ctx context.Context, in *PackagePageReq, opts ...grpc.CallOption) (*PackageListResp, error) {
	client := apps.NewSysPackagesClient(m.cli.Conn())
	return client.GetPackageList(ctx, in, opts...)
}

func (m *defaultSysPackages) GetPackageById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*PackageResp, error) {
	client := apps.NewSysPackagesClient(m.cli.Conn())
	return client.GetPackageById(ctx, in, opts...)
}
