// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system_service.proto

package server

import (
	"system-service/rpc/apps/system-service"
	"system-service/rpc/internal/logic"
	"system-service/rpc/internal/svc"
)

type SysUsersServer struct {
	svcCtx *svc.ServiceContext
	system_service.UnimplementedSysUsersServer
}

func NewSysUsersServer(svcCtx *svc.ServiceContext) *SysUsersServer {
	return &SysUsersServer{
		svcCtx: svcCtx,
	}
}

// 定义客户端流式 rpc
func (s *SysUsersServer) GetUserById(stream system_service.SysUsers_GetUserByIdServer) error {
	l := logic.NewGetUserByIdLogic(stream.Context(), s.svcCtx)
	return l.GetUserById(stream)
}

// 定义客户端流式 rpc
func (s *SysUsersServer) GetUserByUsername(stream system_service.SysUsers_GetUserByUsernameServer) error {
	l := logic.NewGetUserByUsernameLogic(stream.Context(), s.svcCtx)
	return l.GetUserByUsername(stream)
}
