// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: basedata_service.proto

package server

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps/system-service"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/logic"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/svc"
)

type SysUsersServer struct {
	svcCtx *svc.ServiceContext
	system_service.UnimplementedSysUsersServer
}

func NewSysUsersServer(svcCtx *svc.ServiceContext) *SysUsersServer {
	return &SysUsersServer{
		svcCtx: svcCtx,
	}
}

// 定义客户端流式 rpc
func (s *SysUsersServer) GetUserById(ctx context.Context, in *system_service.UserReq) (*system_service.User, error) {
	l := logic.NewGetUserByIdLogic(ctx, s.svcCtx)
	return l.GetUserById(in)
}

// 定义客户端流式 rpc
func (s *SysUsersServer) GetUserByUsername(ctx context.Context, in *system_service.UserReq) (*system_service.User, error) {
	l := logic.NewGetUserByUsernameLogic(ctx, s.svcCtx)
	return l.GetUserByUsername(in)
}
