// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"` // 使用omitempty确保没有数据时此字段不会出现在JSON中
}

type Request struct {
	Name string `path:"name,options=you|me"`
}
