// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"github.com/saas-zero/saas-zero-basedata/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/system/api/create",
				Handler: CreateApiHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/api/delete",
				Handler: DeleteApiHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/api/detail",
				Handler: GetApiDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/api/list",
				Handler: GetApiListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/api/update",
				Handler: UpdateApiHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dept/create",
				Handler: CreateDeptHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dept/delete",
				Handler: DeleteDeptHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dept/detail",
				Handler: GetDeptDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dept/list",
				Handler: GetDeptListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dept/tree",
				Handler: GetDeptTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dept/update",
				Handler: UpdateDeptHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dict/create",
				Handler: CreateDictHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dict/delete",
				Handler: DeleteDictHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dict/detail",
				Handler: GetDictDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dict/list",
				Handler: GetDictListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dict/update",
				Handler: UpdateDictHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dictData/byDictKey",
				Handler: GetDictDataByDictKeyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dictData/create",
				Handler: CreateDictDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dictData/delete",
				Handler: DeleteDictDataHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dictData/detail",
				Handler: GetDictDataDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/dictData/list",
				Handler: GetDictDataListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/dictData/update",
				Handler: UpdateDictDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/menu/create",
				Handler: CreateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/menu/delete",
				Handler: DeleteMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/menu/detail",
				Handler: GetMenuDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/menu/list",
				Handler: GetMenuListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/menu/routers",
				Handler: GetMenuRoutersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/menu/tree",
				Handler: GetMenuTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/menu/update",
				Handler: UpdateMenuHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/package/create",
				Handler: CreatePackageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/package/delete",
				Handler: DeletePackageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/package/detail",
				Handler: GetPackageDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/package/list",
				Handler: GetPackageListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/package/update",
				Handler: UpdatePackageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/role/assignApis",
				Handler: AssignApisHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/role/assignMenus",
				Handler: AssignMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/role/create",
				Handler: CreateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/role/delete",
				Handler: DeleteRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/role/detail",
				Handler: GetRoleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/role/list",
				Handler: GetRoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/role/update",
				Handler: UpdateRoleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/tenant/changeStatus",
				Handler: ChangeTenantStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/tenant/create",
				Handler: CreateTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/tenant/delete",
				Handler: DeleteTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/tenant/detail",
				Handler: GetTenantDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/tenant/list",
				Handler: GetTenantListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/tenant/update",
				Handler: UpdateTenantHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/user/assignRoles",
				Handler: AssignRolesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/user/create",
				Handler: CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/user/delete",
				Handler: DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/user/detail",
				Handler: GetUserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/system/user/list",
				Handler: GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/user/resetPassword",
				Handler: ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/user/update",
				Handler: UpdateUserHandler(serverCtx),
			},
		},
	)
}
