// Code generated by ent, DO NOT EDIT.

package sysapi

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sysapi type in the database.
	Label = "sys_api"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedID holds the string denoting the created_id field in the database.
	FieldCreatedID = "created_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldAPIName holds the string denoting the api_name field in the database.
	FieldAPIName = "api_name"
	// FieldAPIType holds the string denoting the api_type field in the database.
	FieldAPIType = "api_type"
	// FieldAPIPath holds the string denoting the api_path field in the database.
	FieldAPIPath = "api_path"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldMethod holds the string denoting the method field in the database.
	FieldMethod = "method"
	// EdgeRoles holds the string denoting the roles edge name in mutations.
	EdgeRoles = "roles"
	// Table holds the table name of the sysapi in the database.
	Table = "sys_apis"
	// RolesTable is the table that holds the roles relation/edge. The primary key declared below.
	RolesTable = "sys_role_apis"
	// RolesInverseTable is the table name for the SysRole entity.
	// It exists in this package in order to avoid circular dependency with the "sysrole" package.
	RolesInverseTable = "sys_roles"
)

// Columns holds all SQL columns for sysapi fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCreatedID,
	FieldCreatedBy,
	FieldStatus,
	FieldRemark,
	FieldAPIName,
	FieldAPIType,
	FieldAPIPath,
	FieldServiceName,
	FieldMethod,
}

var (
	// RolesPrimaryKey and RolesColumn2 are the table columns denoting the
	// primary key for the roles relation (M2M).
	RolesPrimaryKey = []string{"sys_role_id", "sys_api_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	CreatedIDValidator func(int64) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// DefaultAPIName holds the default value on creation for the "api_name" field.
	DefaultAPIName string
	// APINameValidator is a validator for the "api_name" field. It is called by the builders before save.
	APINameValidator func(string) error
	// DefaultAPIPath holds the default value on creation for the "api_path" field.
	DefaultAPIPath string
	// APIPathValidator is a validator for the "api_path" field. It is called by the builders before save.
	APIPathValidator func(string) error
	// DefaultServiceName holds the default value on creation for the "service_name" field.
	DefaultServiceName string
	// ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	ServiceNameValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusInactive  Status = "inactive"
	StatusSuspended Status = "suspended"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusSuspended:
		return nil
	default:
		return fmt.Errorf("sysapi: invalid enum value for status field: %q", s)
	}
}

// APIType defines the type for the "api_type" enum field.
type APIType string

// APITypeGroup is the default value of the APIType enum.
const DefaultAPIType = APITypeGroup

// APIType values.
const (
	APITypeGroup APIType = "group"
	APITypeAPI   APIType = "api"
)

func (at APIType) String() string {
	return string(at)
}

// APITypeValidator is a validator for the "api_type" field enum values. It is called by the builders before save.
func APITypeValidator(at APIType) error {
	switch at {
	case APITypeGroup, APITypeAPI:
		return nil
	default:
		return fmt.Errorf("sysapi: invalid enum value for api_type field: %q", at)
	}
}

// Method defines the type for the "method" enum field.
type Method string

// Method values.
const (
	MethodGet    Method = "get"
	MethodPost   Method = "post"
	MethodPut    Method = "put"
	MethodDelete Method = "delete"
)

func (m Method) String() string {
	return string(m)
}

// MethodValidator is a validator for the "method" field enum values. It is called by the builders before save.
func MethodValidator(m Method) error {
	switch m {
	case MethodGet, MethodPost, MethodPut, MethodDelete:
		return nil
	default:
		return fmt.Errorf("sysapi: invalid enum value for method field: %q", m)
	}
}

// OrderOption defines the ordering options for the SysApi queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCreatedID orders the results by the created_id field.
func ByCreatedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByAPIName orders the results by the api_name field.
func ByAPIName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIName, opts...).ToFunc()
}

// ByAPIType orders the results by the api_type field.
func ByAPIType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIType, opts...).ToFunc()
}

// ByAPIPath orders the results by the api_path field.
func ByAPIPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIPath, opts...).ToFunc()
}

// ByServiceName orders the results by the service_name field.
func ByServiceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceName, opts...).ToFunc()
}

// ByMethod orders the results by the method field.
func ByMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMethod, opts...).ToFunc()
}

// ByRolesCount orders the results by roles count.
func ByRolesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRolesStep(), opts...)
	}
}

// ByRoles orders the results by roles terms.
func ByRoles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRolesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRolesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RolesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, RolesTable, RolesPrimaryKey...),
	)
}
