// Code generated by ent, DO NOT EDIT.

package sysapi

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/saas-zero/saas-zero-basedata/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedID applies equality check predicate on the "created_id" field. It's identical to CreatedIDEQ.
func CreatedID(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedID applies equality check predicate on the "updated_id" field. It's identical to UpdatedIDEQ.
func UpdatedID(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldUpdatedID, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedID applies equality check predicate on the "deleted_id" field. It's identical to DeletedIDEQ.
func DeletedID(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldDeletedID, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldDeletedBy, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldRemark, v))
}

// APIName applies equality check predicate on the "api_name" field. It's identical to APINameEQ.
func APIName(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldAPIName, v))
}

// APIPath applies equality check predicate on the "api_path" field. It's identical to APIPathEQ.
func APIPath(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldAPIPath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedIDEQ applies the EQ predicate on the "created_id" field.
func CreatedIDEQ(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedIDNEQ applies the NEQ predicate on the "created_id" field.
func CreatedIDNEQ(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldCreatedID, v))
}

// CreatedIDIn applies the In predicate on the "created_id" field.
func CreatedIDIn(vs ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldCreatedID, vs...))
}

// CreatedIDNotIn applies the NotIn predicate on the "created_id" field.
func CreatedIDNotIn(vs ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldCreatedID, vs...))
}

// CreatedIDGT applies the GT predicate on the "created_id" field.
func CreatedIDGT(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldCreatedID, v))
}

// CreatedIDGTE applies the GTE predicate on the "created_id" field.
func CreatedIDGTE(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldCreatedID, v))
}

// CreatedIDLT applies the LT predicate on the "created_id" field.
func CreatedIDLT(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldCreatedID, v))
}

// CreatedIDLTE applies the LTE predicate on the "created_id" field.
func CreatedIDLTE(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldCreatedID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedIDEQ applies the EQ predicate on the "updated_id" field.
func UpdatedIDEQ(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldUpdatedID, v))
}

// UpdatedIDNEQ applies the NEQ predicate on the "updated_id" field.
func UpdatedIDNEQ(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldUpdatedID, v))
}

// UpdatedIDIn applies the In predicate on the "updated_id" field.
func UpdatedIDIn(vs ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldUpdatedID, vs...))
}

// UpdatedIDNotIn applies the NotIn predicate on the "updated_id" field.
func UpdatedIDNotIn(vs ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldUpdatedID, vs...))
}

// UpdatedIDGT applies the GT predicate on the "updated_id" field.
func UpdatedIDGT(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldUpdatedID, v))
}

// UpdatedIDGTE applies the GTE predicate on the "updated_id" field.
func UpdatedIDGTE(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldUpdatedID, v))
}

// UpdatedIDLT applies the LT predicate on the "updated_id" field.
func UpdatedIDLT(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldUpdatedID, v))
}

// UpdatedIDLTE applies the LTE predicate on the "updated_id" field.
func UpdatedIDLTE(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldUpdatedID, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedIDEQ applies the EQ predicate on the "deleted_id" field.
func DeletedIDEQ(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldDeletedID, v))
}

// DeletedIDNEQ applies the NEQ predicate on the "deleted_id" field.
func DeletedIDNEQ(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldDeletedID, v))
}

// DeletedIDIn applies the In predicate on the "deleted_id" field.
func DeletedIDIn(vs ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldDeletedID, vs...))
}

// DeletedIDNotIn applies the NotIn predicate on the "deleted_id" field.
func DeletedIDNotIn(vs ...int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldDeletedID, vs...))
}

// DeletedIDGT applies the GT predicate on the "deleted_id" field.
func DeletedIDGT(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldDeletedID, v))
}

// DeletedIDGTE applies the GTE predicate on the "deleted_id" field.
func DeletedIDGTE(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldDeletedID, v))
}

// DeletedIDLT applies the LT predicate on the "deleted_id" field.
func DeletedIDLT(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldDeletedID, v))
}

// DeletedIDLTE applies the LTE predicate on the "deleted_id" field.
func DeletedIDLTE(v int64) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldDeletedID, v))
}

// DeletedIDIsNil applies the IsNil predicate on the "deleted_id" field.
func DeletedIDIsNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldIsNull(FieldDeletedID))
}

// DeletedIDNotNil applies the NotNil predicate on the "deleted_id" field.
func DeletedIDNotNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldNotNull(FieldDeletedID))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContainsFold(FieldDeletedBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldStatus, vs...))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContainsFold(FieldRemark, v))
}

// APINameEQ applies the EQ predicate on the "api_name" field.
func APINameEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldAPIName, v))
}

// APINameNEQ applies the NEQ predicate on the "api_name" field.
func APINameNEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldAPIName, v))
}

// APINameIn applies the In predicate on the "api_name" field.
func APINameIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldAPIName, vs...))
}

// APINameNotIn applies the NotIn predicate on the "api_name" field.
func APINameNotIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldAPIName, vs...))
}

// APINameGT applies the GT predicate on the "api_name" field.
func APINameGT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldAPIName, v))
}

// APINameGTE applies the GTE predicate on the "api_name" field.
func APINameGTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldAPIName, v))
}

// APINameLT applies the LT predicate on the "api_name" field.
func APINameLT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldAPIName, v))
}

// APINameLTE applies the LTE predicate on the "api_name" field.
func APINameLTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldAPIName, v))
}

// APINameContains applies the Contains predicate on the "api_name" field.
func APINameContains(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContains(FieldAPIName, v))
}

// APINameHasPrefix applies the HasPrefix predicate on the "api_name" field.
func APINameHasPrefix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasPrefix(FieldAPIName, v))
}

// APINameHasSuffix applies the HasSuffix predicate on the "api_name" field.
func APINameHasSuffix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasSuffix(FieldAPIName, v))
}

// APINameEqualFold applies the EqualFold predicate on the "api_name" field.
func APINameEqualFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEqualFold(FieldAPIName, v))
}

// APINameContainsFold applies the ContainsFold predicate on the "api_name" field.
func APINameContainsFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContainsFold(FieldAPIName, v))
}

// APITypeEQ applies the EQ predicate on the "api_type" field.
func APITypeEQ(v APIType) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldAPIType, v))
}

// APITypeNEQ applies the NEQ predicate on the "api_type" field.
func APITypeNEQ(v APIType) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldAPIType, v))
}

// APITypeIn applies the In predicate on the "api_type" field.
func APITypeIn(vs ...APIType) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldAPIType, vs...))
}

// APITypeNotIn applies the NotIn predicate on the "api_type" field.
func APITypeNotIn(vs ...APIType) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldAPIType, vs...))
}

// APIPathEQ applies the EQ predicate on the "api_path" field.
func APIPathEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldAPIPath, v))
}

// APIPathNEQ applies the NEQ predicate on the "api_path" field.
func APIPathNEQ(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldAPIPath, v))
}

// APIPathIn applies the In predicate on the "api_path" field.
func APIPathIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldAPIPath, vs...))
}

// APIPathNotIn applies the NotIn predicate on the "api_path" field.
func APIPathNotIn(vs ...string) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldAPIPath, vs...))
}

// APIPathGT applies the GT predicate on the "api_path" field.
func APIPathGT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGT(FieldAPIPath, v))
}

// APIPathGTE applies the GTE predicate on the "api_path" field.
func APIPathGTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldGTE(FieldAPIPath, v))
}

// APIPathLT applies the LT predicate on the "api_path" field.
func APIPathLT(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLT(FieldAPIPath, v))
}

// APIPathLTE applies the LTE predicate on the "api_path" field.
func APIPathLTE(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldLTE(FieldAPIPath, v))
}

// APIPathContains applies the Contains predicate on the "api_path" field.
func APIPathContains(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContains(FieldAPIPath, v))
}

// APIPathHasPrefix applies the HasPrefix predicate on the "api_path" field.
func APIPathHasPrefix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasPrefix(FieldAPIPath, v))
}

// APIPathHasSuffix applies the HasSuffix predicate on the "api_path" field.
func APIPathHasSuffix(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldHasSuffix(FieldAPIPath, v))
}

// APIPathEqualFold applies the EqualFold predicate on the "api_path" field.
func APIPathEqualFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldEqualFold(FieldAPIPath, v))
}

// APIPathContainsFold applies the ContainsFold predicate on the "api_path" field.
func APIPathContainsFold(v string) predicate.SysApi {
	return predicate.SysApi(sql.FieldContainsFold(FieldAPIPath, v))
}

// APIMethodEQ applies the EQ predicate on the "api_method" field.
func APIMethodEQ(v APIMethod) predicate.SysApi {
	return predicate.SysApi(sql.FieldEQ(FieldAPIMethod, v))
}

// APIMethodNEQ applies the NEQ predicate on the "api_method" field.
func APIMethodNEQ(v APIMethod) predicate.SysApi {
	return predicate.SysApi(sql.FieldNEQ(FieldAPIMethod, v))
}

// APIMethodIn applies the In predicate on the "api_method" field.
func APIMethodIn(vs ...APIMethod) predicate.SysApi {
	return predicate.SysApi(sql.FieldIn(FieldAPIMethod, vs...))
}

// APIMethodNotIn applies the NotIn predicate on the "api_method" field.
func APIMethodNotIn(vs ...APIMethod) predicate.SysApi {
	return predicate.SysApi(sql.FieldNotIn(FieldAPIMethod, vs...))
}

// APIMethodIsNil applies the IsNil predicate on the "api_method" field.
func APIMethodIsNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldIsNull(FieldAPIMethod))
}

// APIMethodNotNil applies the NotNil predicate on the "api_method" field.
func APIMethodNotNil() predicate.SysApi {
	return predicate.SysApi(sql.FieldNotNull(FieldAPIMethod))
}

// HasPackages applies the HasEdge predicate on the "packages" edge.
func HasPackages() predicate.SysApi {
	return predicate.SysApi(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, PackagesTable, PackagesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPackagesWith applies the HasEdge predicate on the "packages" edge with a given conditions (other predicates).
func HasPackagesWith(preds ...predicate.SysPackage) predicate.SysApi {
	return predicate.SysApi(func(s *sql.Selector) {
		step := newPackagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysApi) predicate.SysApi {
	return predicate.SysApi(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysApi) predicate.SysApi {
	return predicate.SysApi(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysApi) predicate.SysApi {
	return predicate.SysApi(sql.NotPredicates(p))
}
