// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package sysdicts

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DictListResp = apps.DictListResp
	DictPageReq  = apps.DictPageReq
	DictReq      = apps.DictReq
	DictResp     = apps.DictResp
	EmptyResp    = apps.EmptyResp
	IdReq        = apps.IdReq
	IdsReq       = apps.IdsReq

	SysDicts interface {
		CreateDict(ctx context.Context, in *DictReq, opts ...grpc.CallOption) (*DictResp, error)
		UpdateDict(ctx context.Context, in *DictReq, opts ...grpc.CallOption) (*DictResp, error)
		DeleteDict(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error)
		GetDictList(ctx context.Context, in *DictPageReq, opts ...grpc.CallOption) (*DictListResp, error)
		GetDictById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*DictResp, error)
	}

	defaultSysDicts struct {
		cli zrpc.Client
	}
)

func NewSysDicts(cli zrpc.Client) SysDicts {
	return &defaultSysDicts{
		cli: cli,
	}
}

func (m *defaultSysDicts) CreateDict(ctx context.Context, in *DictReq, opts ...grpc.CallOption) (*DictResp, error) {
	client := apps.NewSysDictsClient(m.cli.Conn())
	return client.CreateDict(ctx, in, opts...)
}

func (m *defaultSysDicts) UpdateDict(ctx context.Context, in *DictReq, opts ...grpc.CallOption) (*DictResp, error) {
	client := apps.NewSysDictsClient(m.cli.Conn())
	return client.UpdateDict(ctx, in, opts...)
}

func (m *defaultSysDicts) DeleteDict(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := apps.NewSysDictsClient(m.cli.Conn())
	return client.DeleteDict(ctx, in, opts...)
}

func (m *defaultSysDicts) GetDictList(ctx context.Context, in *DictPageReq, opts ...grpc.CallOption) (*DictListResp, error) {
	client := apps.NewSysDictsClient(m.cli.Conn())
	return client.GetDictList(ctx, in, opts...)
}

func (m *defaultSysDicts) GetDictById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*DictResp, error) {
	client := apps.NewSysDictsClient(m.cli.Conn())
	return client.GetDictById(ctx, in, opts...)
}
