// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/saas-zero/saas-zero-common/pkg/ent/mixins"
)

type SysUser struct {
	ent.Schema
}

func (SysUser) Fields() []ent.Field {
	return []ent.Field{
		field.String("username").Immutable().Unique().NotEmpty().MaxLen(128).Comment("名称，不能为空"),
		field.String("password").NotEmpty().MaxLen(255).Comment("密码，不能为空"),
		field.String("nickname").Default("").MaxLen(128).Comment("昵称，不能为空"),
		field.String("mobile").Default("").MaxLen(20).Comment("手机号码,注意国外的号码"),
		field.String("email").Default("").MaxLen(64).Comment("邮箱地址"),
		field.String("avatar").Default("").Comment("头像路径"),
		field.Int64("dept_id").Default(0).Positive().Comment("部门ID，不能为空"),

		//// 最后登录时间
		//field.Time("last_login_time").
		//	Optional().
		//	Comment("最后登录时间"),
		//
		//// 最后登录IP
		//field.String("last_login_ip").
		//	Optional().
		//	MaxLen(45).  // 支持IPv6
		//	Comment("最后登录IP"),
		//
		//// 登录失败次数
		//field.Int32("login_failures").
		//	Default(0).
		//	Comment("登录失败次数"),
		//
		//// 账户锁定时间
		//field.Time("locked_until").
		//	Optional().
		//	Comment("账户锁定截止时间"),
		//
		//// 密码修改时间
		//field.Time("password_changed_at").
		//	Optional().
		//	Comment("密码最后修改时间"),
	}
}

func (SysUser) Mixin() []ent.Mixin {
	return []ent.Mixin{
		mixins.BaseMixin{},
		mixins.TenantMixin{},
		mixins.CreatedMixin{},
		mixins.UpdatedMixin{},
		mixins.DeletedMixin{},
		mixins.StatusMixin{},
		mixins.RemarkMixin{},
	}
}

//func (SysUser) Edges() []ent.Edge {
//	return []ent.Edge{
//		edge.From("sys_tenant", SysTenant.Type).Ref("sys_user").Unique().Required().Field("tenant_id"),
//		edge.From("sys_dept", SysDept.Type).Ref("sys_user").Unique().Field("dept_id"),
//	}
//}

//func (SysUser) Edges() []ent.Edge {
//	return []ent.Edge{
//		edge.To("sys_tenant", SysTenant.Type).Field("tenant_id").Unique().Required(),
//		edge.To("sys_dept", SysDept.Type).Field("dept_id").Unique().Required(),
//		edge.To("roles", SysRole.Type),
//	}
//}

func (SysUser) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("roles", SysRole.Type),
	}
}

func (SysUser) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.WithComments(true),
		schema.Comment("user Table | 用户表"),
		entsql.Annotation{Table: "sys_users"}}
}

func (SysUser) Indexes() []ent.Index {
	return []ent.Index{
		// 租户ID + 用户名的组合索引 - 用于租户内用户名查询
		index.Fields("tenant_id", "username"),

		// 租户ID + 手机号的组合索引 - 用于租户内手机号查询和唯一性
		index.Fields("tenant_id", "mobile"),

		// 租户ID + 邮箱的组合索引 - 用于租户内邮箱查询和唯一性
		index.Fields("tenant_id", "email"),

		// 部门ID索引 - 用于按部门查询用户
		index.Fields("dept_id"),

		// 状态索引 - 用于按状态筛选用户
		index.Fields("status"),

		// 创建时间索引 - 用于时间范围查询和排序
		index.Fields("created_at"),

		// 租户ID + 状态的组合索引 - 常用查询场景
		index.Fields("tenant_id", "status"),

		// 租户ID + 部门ID的组合索引 - 常用查询场景
		index.Fields("tenant_id", "dept_id"),
	}
}
