// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/saas-zero/saas-zero-common/pkg/ent/mixins"
)

type SysDictData struct {
	ent.Schema
}

func (SysDictData) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").NotEmpty().MaxLen(128).Comment("名称，不能为空"),
		field.String("key").NotEmpty().MaxLen(128).Comment("key，不能为空"),
		field.String("value").NotEmpty().MaxLen(128).Comment("值，不能为空"),
		field.Int64("dict_id").Default(0).Positive().Comment("字典ID，不能为空"),
	}
}

func (SysDictData) Mixin() []ent.Mixin {
	return []ent.Mixin{
		mixins.BaseMixin{},
		mixins.TenantMixin{},
		mixins.CreatedMixin{},
		mixins.UpdatedMixin{},
		mixins.DeletedMixin{},
		mixins.StatusMixin{},
		mixins.RemarkMixin{},
	}
}

func (SysDictData) Edges() []ent.Edge {
	return nil
}
func (SysDictData) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.WithComments(true),
		schema.Comment("dict data Table | 字典数据表"),
		entsql.Annotation{Table: "sys_dict_datas"}}
}

func (SysDictData) Indexes() []ent.Index {
	return []ent.Index{
		// 1. 按字典ID查询的索引（常用查询场景）
		index.Fields("dict_id"),

		// 2. 按状态查询的索引（管理后台常用）
		index.Fields("status"),

		// 3. 租户级别的唯一约束：同一个租户内，同一字典下的key不能重复
		index.Fields("tenant_id", "dict_id", "key").Unique(),

		// 4. 复合查询索引：按租户+字典+状态查询
		index.Fields("tenant_id", "dict_id", "status"),
	}
}
