// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"entgo.io/ent"
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
	"entgo.io/ent/schema/index"
	"github.com/saas-zero/saas-zero-common/pkg/ent/mixins"
)

type SysTenant struct {
	ent.Schema
}

func (SysTenant) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").Unique().NotEmpty().MaxLen(128).Comment("名称，不能为空"),
		field.String("code").Unique().NotEmpty().MaxLen(128).Comment("编码，不能为空"),
		field.Int64("admin_id").Positive().Comment("管理员id，不能为空，创建租户的时候顺便创建用户"),
		field.Int64("parent_id").Positive().Default(0).Comment("父级id，不能为空,0为第一级"),
		//field.Time("expire_time").Optional(),
	}
}
func (SysTenant) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("roles", SysRole.Type),
	}
}

func (SysTenant) Mixin() []ent.Mixin {
	return []ent.Mixin{
		mixins.BaseMixin{},
		mixins.CreatedMixin{},
		mixins.UpdatedMixin{},
		mixins.DeletedMixin{},
		mixins.StatusMixin{},
		mixins.RemarkMixin{},
	}
}

func (SysTenant) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entsql.WithComments(true),
		schema.Comment("tenant Table | 租户表"),
		entsql.Annotation{Table: "sys_tenants"}}
}

func (SysTenant) Indexes() []ent.Index {
	return []ent.Index{
		// 复合索引：按租户和状态查询
		index.Fields("id", "status"),
		// 复合索引：按租户和状态查询
		index.Fields("parent_id", "status"),
	}
}
