// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package sysroles

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyResp    = apps.EmptyResp
	IdReq        = apps.IdReq
	IdsReq       = apps.IdsReq
	RoleListResp = apps.RoleListResp
	RolePageReq  = apps.RolePageReq
	RoleReq      = apps.RoleReq
	RoleResp     = apps.RoleResp

	SysRoles interface {
		CreateRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*RoleResp, error)
		UpdateRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*RoleResp, error)
		DeleteRole(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error)
		GetRoleList(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RoleListResp, error)
		GetRoleById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RoleResp, error)
		AssignMenus(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*EmptyResp, error)
		AssignApis(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*EmptyResp, error)
	}

	defaultSysRoles struct {
		cli zrpc.Client
	}
)

func NewSysRoles(cli zrpc.Client) SysRoles {
	return &defaultSysRoles{
		cli: cli,
	}
}

func (m *defaultSysRoles) CreateRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*RoleResp, error) {
	client := apps.NewSysRolesClient(m.cli.Conn())
	return client.CreateRole(ctx, in, opts...)
}

func (m *defaultSysRoles) UpdateRole(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*RoleResp, error) {
	client := apps.NewSysRolesClient(m.cli.Conn())
	return client.UpdateRole(ctx, in, opts...)
}

func (m *defaultSysRoles) DeleteRole(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := apps.NewSysRolesClient(m.cli.Conn())
	return client.DeleteRole(ctx, in, opts...)
}

func (m *defaultSysRoles) GetRoleList(ctx context.Context, in *RolePageReq, opts ...grpc.CallOption) (*RoleListResp, error) {
	client := apps.NewSysRolesClient(m.cli.Conn())
	return client.GetRoleList(ctx, in, opts...)
}

func (m *defaultSysRoles) GetRoleById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*RoleResp, error) {
	client := apps.NewSysRolesClient(m.cli.Conn())
	return client.GetRoleById(ctx, in, opts...)
}

func (m *defaultSysRoles) AssignMenus(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := apps.NewSysRolesClient(m.cli.Conn())
	return client.AssignMenus(ctx, in, opts...)
}

func (m *defaultSysRoles) AssignApis(ctx context.Context, in *RoleReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := apps.NewSysRolesClient(m.cli.Conn())
	return client.AssignApis(ctx, in, opts...)
}
