// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysApisColumns holds the columns for the "sys_apis" table.
	SysApisColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "api_name", Type: field.TypeString, Size: 128, Comment: "api名称，type是api时不能为空", Default: ""},
		{Name: "api_type", Type: field.TypeEnum, Comment: "api类型：group分组，api接口，不能为空", Enums: []string{"group", "api"}, Default: "group"},
		{Name: "api_path", Type: field.TypeString, Size: 128, Comment: "api路径，type是api时不能为空", Default: ""},
		{Name: "service_name", Type: field.TypeString, Size: 128, Comment: "微服务名称，type是api时不能为空", Default: ""},
		{Name: "method", Type: field.TypeEnum, Comment: "api接口请求类型，type是api时不能为空", Enums: []string{"get", "post", "put", "delete"}},
	}
	// SysApisTable holds the schema information for the "sys_apis" table.
	SysApisTable = &schema.Table{
		Name:       "sys_apis",
		Comment:    "API Table | 接口表",
		Columns:    SysApisColumns,
		PrimaryKey: []*schema.Column{SysApisColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysapi_service_name_method_status",
				Unique:  false,
				Columns: []*schema.Column{SysApisColumns[9], SysApisColumns[10], SysApisColumns[4]},
			},
			{
				Name:    "sysapi_api_path_service_name",
				Unique:  false,
				Columns: []*schema.Column{SysApisColumns[8], SysApisColumns[9]},
			},
			{
				Name:    "sysapi_api_type",
				Unique:  false,
				Columns: []*schema.Column{SysApisColumns[7]},
			},
			{
				Name:    "sysapi_status",
				Unique:  false,
				Columns: []*schema.Column{SysApisColumns[4]},
			},
			{
				Name:    "idx_service_path_method_unique",
				Unique:  true,
				Columns: []*schema.Column{SysApisColumns[9], SysApisColumns[8], SysApisColumns[10]},
			},
			{
				Name:    "sysapi_service_name_status",
				Unique:  false,
				Columns: []*schema.Column{SysApisColumns[9], SysApisColumns[4]},
			},
		},
	}
	// SysConfigsColumns holds the columns for the "sys_configs" table.
	SysConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "名称，不能为空"},
		{Name: "key", Type: field.TypeString, Unique: true, Size: 128, Comment: "key，不能为空"},
		{Name: "value", Type: field.TypeString, Size: 128, Comment: "值，不能为空"},
	}
	// SysConfigsTable holds the schema information for the "sys_configs" table.
	SysConfigsTable = &schema.Table{
		Name:       "sys_configs",
		Comment:    "config Table | 配置表",
		Columns:    SysConfigsColumns,
		PrimaryKey: []*schema.Column{SysConfigsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysconfig_key_status",
				Unique:  false,
				Columns: []*schema.Column{SysConfigsColumns[10], SysConfigsColumns[7]},
			},
		},
	}
	// SysDeptsColumns holds the columns for the "sys_depts" table.
	SysDeptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "tenant_id", Type: field.TypeInt64, Comment: "租户ID，不能为空"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "sort", Type: field.TypeUint32, Comment: "Sort Number | 排序编号", Default: 1},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 128, Comment: "名称，不能为空"},
		{Name: "mobile", Type: field.TypeString, Comment: "手机号码", Default: ""},
		{Name: "email", Type: field.TypeString, Comment: "邮箱地址", Default: ""},
		{Name: "parent_id", Type: field.TypeInt64, Comment: "父级id，不能为空,0为第一级", Default: 0},
		{Name: "leader_id", Type: field.TypeInt64, Comment: "负责人id，不能为空，创建租户的时候顺便创建用户", Default: 0},
	}
	// SysDeptsTable holds the schema information for the "sys_depts" table.
	SysDeptsTable = &schema.Table{
		Name:       "sys_depts",
		Comment:    "dept Table | 部门表",
		Columns:    SysDeptsColumns,
		PrimaryKey: []*schema.Column{SysDeptsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_depts_sys_users_leader",
				Columns:    []*schema.Column{SysDeptsColumns[17]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sysdept_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysDeptsColumns[1]},
			},
		},
	}
	// SysDictsColumns holds the columns for the "sys_dicts" table.
	SysDictsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "tenant_id", Type: field.TypeInt64, Comment: "租户ID，不能为空"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "名称，不能为空"},
		{Name: "key", Type: field.TypeString, Size: 128, Comment: "key，不能为空"},
		{Name: "is_public", Type: field.TypeBool, Comment: "Whether to be public for everyone | 是否公开词典，无需登录即可访问", Default: false},
	}
	// SysDictsTable holds the schema information for the "sys_dicts" table.
	SysDictsTable = &schema.Table{
		Name:       "sys_dicts",
		Comment:    "dict Table | 字典表",
		Columns:    SysDictsColumns,
		PrimaryKey: []*schema.Column{SysDictsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysdict_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysDictsColumns[1]},
			},
			{
				Name:    "sysdict_tenant_id_key",
				Unique:  true,
				Columns: []*schema.Column{SysDictsColumns[1], SysDictsColumns[14]},
			},
			{
				Name:    "sysdict_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{SysDictsColumns[1], SysDictsColumns[11]},
			},
			{
				Name:    "sysdict_tenant_id_name",
				Unique:  false,
				Columns: []*schema.Column{SysDictsColumns[1], SysDictsColumns[13]},
			},
			{
				Name:    "sysdict_is_public_status",
				Unique:  false,
				Columns: []*schema.Column{SysDictsColumns[15], SysDictsColumns[11]},
			},
		},
	}
	// SysDictDatasColumns holds the columns for the "sys_dict_datas" table.
	SysDictDatasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "tenant_id", Type: field.TypeInt64, Comment: "租户ID，不能为空"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "名称，不能为空"},
		{Name: "key", Type: field.TypeString, Size: 128, Comment: "key，不能为空"},
		{Name: "value", Type: field.TypeString, Size: 128, Comment: "值，不能为空"},
		{Name: "dict_id", Type: field.TypeInt64, Comment: "字典ID，不能为空", Default: 0},
	}
	// SysDictDatasTable holds the schema information for the "sys_dict_datas" table.
	SysDictDatasTable = &schema.Table{
		Name:       "sys_dict_datas",
		Comment:    "dict data Table | 字典数据表",
		Columns:    SysDictDatasColumns,
		PrimaryKey: []*schema.Column{SysDictDatasColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysdictdata_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysDictDatasColumns[1]},
			},
			{
				Name:    "sysdictdata_dict_id",
				Unique:  false,
				Columns: []*schema.Column{SysDictDatasColumns[16]},
			},
			{
				Name:    "sysdictdata_status",
				Unique:  false,
				Columns: []*schema.Column{SysDictDatasColumns[11]},
			},
			{
				Name:    "sysdictdata_tenant_id_dict_id_key",
				Unique:  true,
				Columns: []*schema.Column{SysDictDatasColumns[1], SysDictDatasColumns[16], SysDictDatasColumns[14]},
			},
			{
				Name:    "sysdictdata_tenant_id_dict_id_status",
				Unique:  false,
				Columns: []*schema.Column{SysDictDatasColumns[1], SysDictDatasColumns[16], SysDictDatasColumns[11]},
			},
		},
	}
	// SysMenusColumns holds the columns for the "sys_menus" table.
	SysMenusColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "sort", Type: field.TypeUint32, Comment: "Sort Number | 排序编号", Default: 1},
		{Name: "menu_type", Type: field.TypeEnum, Comment: "类型：directory-目录，menu-菜单，button-按钮", Enums: []string{"directory", "menu", "button"}, Default: "directory"},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "名称，不能为空"},
		{Name: "parent_id", Type: field.TypeInt64, Comment: "父级id，不能为空,0为第一级", Default: 0},
		{Name: "component", Type: field.TypeString, Nullable: true, Comment: "The path of vue file | 组件路径", Default: ""},
		{Name: "path", Type: field.TypeString, Nullable: true, Comment: "Index path | 菜单路由路径", Default: ""},
		{Name: "icon", Type: field.TypeString, Comment: "Menu icon | 菜单图标"},
		{Name: "is_redirect", Type: field.TypeBool, Comment: "是否重定向", Default: false},
		{Name: "redirect", Type: field.TypeString, Nullable: true, Comment: "重定向", Default: ""},
	}
	// SysMenusTable holds the schema information for the "sys_menus" table.
	SysMenusTable = &schema.Table{
		Name:       "sys_menus",
		Comment:    "menu Table | 菜单表",
		Columns:    SysMenusColumns,
		PrimaryKey: []*schema.Column{SysMenusColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysmenu_parent_id_sort",
				Unique:  false,
				Columns: []*schema.Column{SysMenusColumns[15], SysMenusColumns[12]},
			},
			{
				Name:    "sysmenu_path",
				Unique:  false,
				Columns: []*schema.Column{SysMenusColumns[17]},
			},
			{
				Name:    "sysmenu_name",
				Unique:  false,
				Columns: []*schema.Column{SysMenusColumns[14]},
			},
			{
				Name:    "sysmenu_parent_id",
				Unique:  false,
				Columns: []*schema.Column{SysMenusColumns[15]},
			},
			{
				Name:    "sysmenu_menu_type_status",
				Unique:  false,
				Columns: []*schema.Column{SysMenusColumns[13], SysMenusColumns[10]},
			},
		},
	}
	// SysRolesColumns holds the columns for the "sys_roles" table.
	SysRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "sort", Type: field.TypeUint32, Comment: "Sort Number | 排序编号", Default: 1},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "名称，不能为空"},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 128, Comment: "code，不能为空"},
	}
	// SysRolesTable holds the schema information for the "sys_roles" table.
	SysRolesTable = &schema.Table{
		Name:       "sys_roles",
		Comment:    "role Table | 角色表",
		Columns:    SysRolesColumns,
		PrimaryKey: []*schema.Column{SysRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysrole_sort",
				Unique:  false,
				Columns: []*schema.Column{SysRolesColumns[11]},
			},
			{
				Name:    "sysrole_status",
				Unique:  false,
				Columns: []*schema.Column{SysRolesColumns[10]},
			},
		},
	}
	// SysTenantsColumns holds the columns for the "sys_tenants" table.
	SysTenantsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 128, Comment: "名称，不能为空"},
		{Name: "code", Type: field.TypeString, Unique: true, Size: 128, Comment: "编码，不能为空"},
		{Name: "admin_id", Type: field.TypeInt64, Comment: "管理员id，不能为空，创建租户的时候顺便创建用户"},
		{Name: "parent_id", Type: field.TypeInt64, Comment: "父级id，不能为空,0为第一级", Default: 0},
		{Name: "sys_dept_sys_tenant", Type: field.TypeInt64, Nullable: true},
	}
	// SysTenantsTable holds the schema information for the "sys_tenants" table.
	SysTenantsTable = &schema.Table{
		Name:       "sys_tenants",
		Comment:    "tenant Table | 租户表",
		Columns:    SysTenantsColumns,
		PrimaryKey: []*schema.Column{SysTenantsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_tenants_sys_depts_sys_tenant",
				Columns:    []*schema.Column{SysTenantsColumns[16]},
				RefColumns: []*schema.Column{SysDeptsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "systenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{SysTenantsColumns[0], SysTenantsColumns[10]},
			},
			{
				Name:    "systenant_parent_id_status",
				Unique:  false,
				Columns: []*schema.Column{SysTenantsColumns[15], SysTenantsColumns[10]},
			},
		},
	}
	// SysUsersColumns holds the columns for the "sys_users" table.
	SysUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "tenant_id", Type: field.TypeInt64, Comment: "租户ID，不能为空"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 128, Comment: "名称，不能为空"},
		{Name: "password", Type: field.TypeString, Size: 255, Comment: "密码，不能为空"},
		{Name: "nickname", Type: field.TypeString, Size: 128, Comment: "昵称，不能为空", Default: ""},
		{Name: "mobile", Type: field.TypeString, Size: 20, Comment: "手机号码,注意国外的号码", Default: ""},
		{Name: "email", Type: field.TypeString, Size: 64, Comment: "邮箱地址", Default: ""},
		{Name: "avatar", Type: field.TypeString, Comment: "头像路径", Default: ""},
		{Name: "dept_id", Type: field.TypeInt64, Comment: "部门ID，不能为空", Default: 0},
		{Name: "sys_dept_sys_user", Type: field.TypeInt64, Nullable: true},
	}
	// SysUsersTable holds the schema information for the "sys_users" table.
	SysUsersTable = &schema.Table{
		Name:       "sys_users",
		Comment:    "user Table | 用户表",
		Columns:    SysUsersColumns,
		PrimaryKey: []*schema.Column{SysUsersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_users_sys_depts_sys_user",
				Columns:    []*schema.Column{SysUsersColumns[20]},
				RefColumns: []*schema.Column{SysDeptsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "sysuser_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[1]},
			},
			{
				Name:    "sysuser_tenant_id_username",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[1], SysUsersColumns[13]},
			},
			{
				Name:    "sysuser_tenant_id_mobile",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[1], SysUsersColumns[16]},
			},
			{
				Name:    "sysuser_tenant_id_email",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[1], SysUsersColumns[17]},
			},
			{
				Name:    "sysuser_dept_id",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[19]},
			},
			{
				Name:    "sysuser_status",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[11]},
			},
			{
				Name:    "sysuser_created_at",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[2]},
			},
			{
				Name:    "sysuser_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[1], SysUsersColumns[11]},
			},
			{
				Name:    "sysuser_tenant_id_dept_id",
				Unique:  false,
				Columns: []*schema.Column{SysUsersColumns[1], SysUsersColumns[19]},
			},
		},
	}
	// SysRoleMenusColumns holds the columns for the "sys_role_menus" table.
	SysRoleMenusColumns = []*schema.Column{
		{Name: "sys_role_id", Type: field.TypeInt64},
		{Name: "sys_menu_id", Type: field.TypeInt64},
	}
	// SysRoleMenusTable holds the schema information for the "sys_role_menus" table.
	SysRoleMenusTable = &schema.Table{
		Name:       "sys_role_menus",
		Columns:    SysRoleMenusColumns,
		PrimaryKey: []*schema.Column{SysRoleMenusColumns[0], SysRoleMenusColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_role_menus_sys_role_id",
				Columns:    []*schema.Column{SysRoleMenusColumns[0]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "sys_role_menus_sys_menu_id",
				Columns:    []*schema.Column{SysRoleMenusColumns[1]},
				RefColumns: []*schema.Column{SysMenusColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// SysRoleApisColumns holds the columns for the "sys_role_apis" table.
	SysRoleApisColumns = []*schema.Column{
		{Name: "sys_role_id", Type: field.TypeInt64},
		{Name: "sys_api_id", Type: field.TypeInt64},
	}
	// SysRoleApisTable holds the schema information for the "sys_role_apis" table.
	SysRoleApisTable = &schema.Table{
		Name:       "sys_role_apis",
		Columns:    SysRoleApisColumns,
		PrimaryKey: []*schema.Column{SysRoleApisColumns[0], SysRoleApisColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_role_apis_sys_role_id",
				Columns:    []*schema.Column{SysRoleApisColumns[0]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "sys_role_apis_sys_api_id",
				Columns:    []*schema.Column{SysRoleApisColumns[1]},
				RefColumns: []*schema.Column{SysApisColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// SysTenantRolesColumns holds the columns for the "sys_tenant_roles" table.
	SysTenantRolesColumns = []*schema.Column{
		{Name: "sys_tenant_id", Type: field.TypeInt64},
		{Name: "sys_role_id", Type: field.TypeInt64},
	}
	// SysTenantRolesTable holds the schema information for the "sys_tenant_roles" table.
	SysTenantRolesTable = &schema.Table{
		Name:       "sys_tenant_roles",
		Columns:    SysTenantRolesColumns,
		PrimaryKey: []*schema.Column{SysTenantRolesColumns[0], SysTenantRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_tenant_roles_sys_tenant_id",
				Columns:    []*schema.Column{SysTenantRolesColumns[0]},
				RefColumns: []*schema.Column{SysTenantsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "sys_tenant_roles_sys_role_id",
				Columns:    []*schema.Column{SysTenantRolesColumns[1]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// SysUserRolesColumns holds the columns for the "sys_user_roles" table.
	SysUserRolesColumns = []*schema.Column{
		{Name: "sys_user_id", Type: field.TypeInt64},
		{Name: "sys_role_id", Type: field.TypeInt64},
	}
	// SysUserRolesTable holds the schema information for the "sys_user_roles" table.
	SysUserRolesTable = &schema.Table{
		Name:       "sys_user_roles",
		Columns:    SysUserRolesColumns,
		PrimaryKey: []*schema.Column{SysUserRolesColumns[0], SysUserRolesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sys_user_roles_sys_user_id",
				Columns:    []*schema.Column{SysUserRolesColumns[0]},
				RefColumns: []*schema.Column{SysUsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "sys_user_roles_sys_role_id",
				Columns:    []*schema.Column{SysUserRolesColumns[1]},
				RefColumns: []*schema.Column{SysRolesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysApisTable,
		SysConfigsTable,
		SysDeptsTable,
		SysDictsTable,
		SysDictDatasTable,
		SysMenusTable,
		SysRolesTable,
		SysTenantsTable,
		SysUsersTable,
		SysRoleMenusTable,
		SysRoleApisTable,
		SysTenantRolesTable,
		SysUserRolesTable,
	}
)

func init() {
	SysApisTable.Annotation = &entsql.Annotation{
		Table: "sys_apis",
	}
	SysConfigsTable.Annotation = &entsql.Annotation{
		Table: "sys_configs",
	}
	SysDeptsTable.ForeignKeys[0].RefTable = SysUsersTable
	SysDeptsTable.Annotation = &entsql.Annotation{
		Table: "sys_depts",
	}
	SysDictsTable.Annotation = &entsql.Annotation{
		Table: "sys_dicts",
	}
	SysDictDatasTable.Annotation = &entsql.Annotation{
		Table: "sys_dict_datas",
	}
	SysMenusTable.Annotation = &entsql.Annotation{
		Table: "sys_menus",
	}
	SysRolesTable.Annotation = &entsql.Annotation{
		Table: "sys_roles",
	}
	SysTenantsTable.ForeignKeys[0].RefTable = SysDeptsTable
	SysTenantsTable.Annotation = &entsql.Annotation{
		Table: "sys_tenants",
	}
	SysUsersTable.ForeignKeys[0].RefTable = SysDeptsTable
	SysUsersTable.Annotation = &entsql.Annotation{
		Table: "sys_users",
	}
	SysRoleMenusTable.ForeignKeys[0].RefTable = SysRolesTable
	SysRoleMenusTable.ForeignKeys[1].RefTable = SysMenusTable
	SysRoleApisTable.ForeignKeys[0].RefTable = SysRolesTable
	SysRoleApisTable.ForeignKeys[1].RefTable = SysApisTable
	SysTenantRolesTable.ForeignKeys[0].RefTable = SysTenantsTable
	SysTenantRolesTable.ForeignKeys[1].RefTable = SysRolesTable
	SysUserRolesTable.ForeignKeys[0].RefTable = SysUsersTable
	SysUserRolesTable.ForeignKeys[1].RefTable = SysRolesTable
}
