// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: system_service.proto

package sysusers

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps/system-service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	User    = system_service.User
	UserReq = system_service.UserReq

	SysUsers interface {
		// 定义客户端流式 rpc
		GetUserById(ctx context.Context, opts ...grpc.CallOption) (system_service.SysUsers_GetUserByIdClient, error)
		// 定义客户端流式 rpc
		GetUserByUsername(ctx context.Context, opts ...grpc.CallOption) (system_service.SysUsers_GetUserByUsernameClient, error)
	}

	defaultSysUsers struct {
		cli zrpc.Client
	}
)

func NewSysUsers(cli zrpc.Client) SysUsers {
	return &defaultSysUsers{
		cli: cli,
	}
}

// 定义客户端流式 rpc
func (m *defaultSysUsers) GetUserById(ctx context.Context, opts ...grpc.CallOption) (system_service.SysUsers_GetUserByIdClient, error) {
	client := system_service.NewSysUsersClient(m.cli.Conn())
	return client.GetUserById(ctx, opts...)
}

// 定义客户端流式 rpc
func (m *defaultSysUsers) GetUserByUsername(ctx context.Context, opts ...grpc.CallOption) (system_service.SysUsers_GetUserByUsernameClient, error) {
	client := system_service.NewSysUsersClient(m.cli.Conn())
	return client.GetUserByUsername(ctx, opts...)
}
