// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: basedata_service.proto

package sysusers

import (
	"context"

	system_service "github.com/saas-zero/saas-zero-basedata/rpc/apps/system-service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	User    = system_service.User
	UserReq = system_service.UserReq

	SysUsers interface {
		// 根据ID获取用户信息
		GetUserById(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error)
		// 根据用户名获取用户信息
		GetUserByUsername(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error)
	}

	defaultSysUsers struct {
		cli zrpc.Client
	}
)

func NewSysUsers(cli zrpc.Client) SysUsers {
	return &defaultSysUsers{
		cli: cli,
	}
}

// 根据ID获取用户信息
func (m *defaultSysUsers) GetUserById(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error) {
	client := system_service.NewSysUsersClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

// 根据用户名获取用户信息
func (m *defaultSysUsers) GetUserByUsername(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*User, error) {
	client := system_service.NewSysUsersClient(m.cli.Conn())
	return client.GetUserByUsername(ctx, in, opts...)
}