// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/saas-zero/saas-zero-basedata/ent/schema"
	"github.com/saas-zero/saas-zero-basedata/ent/sysapi"
	"github.com/saas-zero/saas-zero-basedata/ent/sysconfig"
	"github.com/saas-zero/saas-zero-basedata/ent/sysdept"
	"github.com/saas-zero/saas-zero-basedata/ent/sysdict"
	"github.com/saas-zero/saas-zero-basedata/ent/sysdictdata"
	"github.com/saas-zero/saas-zero-basedata/ent/sysmenu"
	"github.com/saas-zero/saas-zero-basedata/ent/sysrole"
	"github.com/saas-zero/saas-zero-basedata/ent/systenant"
	"github.com/saas-zero/saas-zero-basedata/ent/sysuser"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sysapiMixin := schema.SysApi{}.Mixin()
	sysapiMixinFields0 := sysapiMixin[0].Fields()
	_ = sysapiMixinFields0
	sysapiMixinFields1 := sysapiMixin[1].Fields()
	_ = sysapiMixinFields1
	sysapiMixinFields2 := sysapiMixin[2].Fields()
	_ = sysapiMixinFields2
	sysapiMixinFields3 := sysapiMixin[3].Fields()
	_ = sysapiMixinFields3
	sysapiFields := schema.SysApi{}.Fields()
	_ = sysapiFields
	// sysapiDescCreatedAt is the schema descriptor for created_at field.
	sysapiDescCreatedAt := sysapiMixinFields1[0].Descriptor()
	// sysapi.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysapi.DefaultCreatedAt = sysapiDescCreatedAt.Default.(func() time.Time)
	// sysapiDescCreatedID is the schema descriptor for created_id field.
	sysapiDescCreatedID := sysapiMixinFields1[1].Descriptor()
	// sysapi.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysapi.CreatedIDValidator = sysapiDescCreatedID.Validators[0].(func(int64) error)
	// sysapiDescCreatedBy is the schema descriptor for created_by field.
	sysapiDescCreatedBy := sysapiMixinFields1[2].Descriptor()
	// sysapi.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysapi.CreatedByValidator = func() func(string) error {
		validators := sysapiDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysapiDescRemark is the schema descriptor for remark field.
	sysapiDescRemark := sysapiMixinFields3[0].Descriptor()
	// sysapi.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysapi.RemarkValidator = sysapiDescRemark.Validators[0].(func(string) error)
	// sysapiDescAPIName is the schema descriptor for api_name field.
	sysapiDescAPIName := sysapiFields[0].Descriptor()
	// sysapi.DefaultAPIName holds the default value on creation for the api_name field.
	sysapi.DefaultAPIName = sysapiDescAPIName.Default.(string)
	// sysapi.APINameValidator is a validator for the "api_name" field. It is called by the builders before save.
	sysapi.APINameValidator = sysapiDescAPIName.Validators[0].(func(string) error)
	// sysapiDescAPIPath is the schema descriptor for api_path field.
	sysapiDescAPIPath := sysapiFields[2].Descriptor()
	// sysapi.DefaultAPIPath holds the default value on creation for the api_path field.
	sysapi.DefaultAPIPath = sysapiDescAPIPath.Default.(string)
	// sysapi.APIPathValidator is a validator for the "api_path" field. It is called by the builders before save.
	sysapi.APIPathValidator = sysapiDescAPIPath.Validators[0].(func(string) error)
	// sysapiDescServiceName is the schema descriptor for service_name field.
	sysapiDescServiceName := sysapiFields[3].Descriptor()
	// sysapi.DefaultServiceName holds the default value on creation for the service_name field.
	sysapi.DefaultServiceName = sysapiDescServiceName.Default.(string)
	// sysapi.ServiceNameValidator is a validator for the "service_name" field. It is called by the builders before save.
	sysapi.ServiceNameValidator = sysapiDescServiceName.Validators[0].(func(string) error)
	// sysapiDescID is the schema descriptor for id field.
	sysapiDescID := sysapiMixinFields0[0].Descriptor()
	// sysapi.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysapi.IDValidator = sysapiDescID.Validators[0].(func(int64) error)
	sysconfigMixin := schema.SysConfig{}.Mixin()
	sysconfigMixinFields0 := sysconfigMixin[0].Fields()
	_ = sysconfigMixinFields0
	sysconfigMixinFields1 := sysconfigMixin[1].Fields()
	_ = sysconfigMixinFields1
	sysconfigMixinFields2 := sysconfigMixin[2].Fields()
	_ = sysconfigMixinFields2
	sysconfigMixinFields3 := sysconfigMixin[3].Fields()
	_ = sysconfigMixinFields3
	sysconfigMixinFields4 := sysconfigMixin[4].Fields()
	_ = sysconfigMixinFields4
	sysconfigFields := schema.SysConfig{}.Fields()
	_ = sysconfigFields
	// sysconfigDescCreatedAt is the schema descriptor for created_at field.
	sysconfigDescCreatedAt := sysconfigMixinFields1[0].Descriptor()
	// sysconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysconfig.DefaultCreatedAt = sysconfigDescCreatedAt.Default.(func() time.Time)
	// sysconfigDescCreatedID is the schema descriptor for created_id field.
	sysconfigDescCreatedID := sysconfigMixinFields1[1].Descriptor()
	// sysconfig.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysconfig.CreatedIDValidator = sysconfigDescCreatedID.Validators[0].(func(int64) error)
	// sysconfigDescCreatedBy is the schema descriptor for created_by field.
	sysconfigDescCreatedBy := sysconfigMixinFields1[2].Descriptor()
	// sysconfig.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysconfig.CreatedByValidator = func() func(string) error {
		validators := sysconfigDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysconfigDescUpdatedAt is the schema descriptor for updated_at field.
	sysconfigDescUpdatedAt := sysconfigMixinFields2[0].Descriptor()
	// sysconfig.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysconfig.DefaultUpdatedAt = sysconfigDescUpdatedAt.Default.(func() time.Time)
	// sysconfigDescUpdatedID is the schema descriptor for updated_id field.
	sysconfigDescUpdatedID := sysconfigMixinFields2[1].Descriptor()
	// sysconfig.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysconfig.UpdatedIDValidator = sysconfigDescUpdatedID.Validators[0].(func(int64) error)
	// sysconfigDescUpdatedBy is the schema descriptor for updated_by field.
	sysconfigDescUpdatedBy := sysconfigMixinFields2[2].Descriptor()
	// sysconfig.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysconfig.UpdatedByValidator = func() func(string) error {
		validators := sysconfigDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysconfigDescRemark is the schema descriptor for remark field.
	sysconfigDescRemark := sysconfigMixinFields4[0].Descriptor()
	// sysconfig.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysconfig.RemarkValidator = sysconfigDescRemark.Validators[0].(func(string) error)
	// sysconfigDescName is the schema descriptor for name field.
	sysconfigDescName := sysconfigFields[0].Descriptor()
	// sysconfig.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysconfig.NameValidator = func() func(string) error {
		validators := sysconfigDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysconfigDescKey is the schema descriptor for key field.
	sysconfigDescKey := sysconfigFields[1].Descriptor()
	// sysconfig.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	sysconfig.KeyValidator = func() func(string) error {
		validators := sysconfigDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysconfigDescValue is the schema descriptor for value field.
	sysconfigDescValue := sysconfigFields[2].Descriptor()
	// sysconfig.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	sysconfig.ValueValidator = func() func(string) error {
		validators := sysconfigDescValue.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(value string) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysconfigDescID is the schema descriptor for id field.
	sysconfigDescID := sysconfigMixinFields0[0].Descriptor()
	// sysconfig.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysconfig.IDValidator = sysconfigDescID.Validators[0].(func(int64) error)
	sysdeptMixin := schema.SysDept{}.Mixin()
	sysdeptMixinFields0 := sysdeptMixin[0].Fields()
	_ = sysdeptMixinFields0
	sysdeptMixinFields1 := sysdeptMixin[1].Fields()
	_ = sysdeptMixinFields1
	sysdeptMixinFields2 := sysdeptMixin[2].Fields()
	_ = sysdeptMixinFields2
	sysdeptMixinFields3 := sysdeptMixin[3].Fields()
	_ = sysdeptMixinFields3
	sysdeptMixinFields4 := sysdeptMixin[4].Fields()
	_ = sysdeptMixinFields4
	sysdeptMixinFields5 := sysdeptMixin[5].Fields()
	_ = sysdeptMixinFields5
	sysdeptMixinFields6 := sysdeptMixin[6].Fields()
	_ = sysdeptMixinFields6
	sysdeptFields := schema.SysDept{}.Fields()
	_ = sysdeptFields
	// sysdeptDescTenantID is the schema descriptor for tenant_id field.
	sysdeptDescTenantID := sysdeptMixinFields1[0].Descriptor()
	// sysdept.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	sysdept.TenantIDValidator = sysdeptDescTenantID.Validators[0].(func(int64) error)
	// sysdeptDescCreatedAt is the schema descriptor for created_at field.
	sysdeptDescCreatedAt := sysdeptMixinFields2[0].Descriptor()
	// sysdept.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysdept.DefaultCreatedAt = sysdeptDescCreatedAt.Default.(func() time.Time)
	// sysdeptDescCreatedID is the schema descriptor for created_id field.
	sysdeptDescCreatedID := sysdeptMixinFields2[1].Descriptor()
	// sysdept.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysdept.CreatedIDValidator = sysdeptDescCreatedID.Validators[0].(func(int64) error)
	// sysdeptDescCreatedBy is the schema descriptor for created_by field.
	sysdeptDescCreatedBy := sysdeptMixinFields2[2].Descriptor()
	// sysdept.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysdept.CreatedByValidator = func() func(string) error {
		validators := sysdeptDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdeptDescUpdatedAt is the schema descriptor for updated_at field.
	sysdeptDescUpdatedAt := sysdeptMixinFields3[0].Descriptor()
	// sysdept.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysdept.DefaultUpdatedAt = sysdeptDescUpdatedAt.Default.(func() time.Time)
	// sysdeptDescUpdatedID is the schema descriptor for updated_id field.
	sysdeptDescUpdatedID := sysdeptMixinFields3[1].Descriptor()
	// sysdept.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysdept.UpdatedIDValidator = sysdeptDescUpdatedID.Validators[0].(func(int64) error)
	// sysdeptDescUpdatedBy is the schema descriptor for updated_by field.
	sysdeptDescUpdatedBy := sysdeptMixinFields3[2].Descriptor()
	// sysdept.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysdept.UpdatedByValidator = func() func(string) error {
		validators := sysdeptDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdeptDescDeletedBy is the schema descriptor for deleted_by field.
	sysdeptDescDeletedBy := sysdeptMixinFields4[2].Descriptor()
	// sysdept.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	sysdept.DeletedByValidator = sysdeptDescDeletedBy.Validators[0].(func(string) error)
	// sysdeptDescSort is the schema descriptor for sort field.
	sysdeptDescSort := sysdeptMixinFields6[0].Descriptor()
	// sysdept.DefaultSort holds the default value on creation for the sort field.
	sysdept.DefaultSort = sysdeptDescSort.Default.(uint32)
	// sysdept.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	sysdept.SortValidator = sysdeptDescSort.Validators[0].(func(uint32) error)
	// sysdeptDescName is the schema descriptor for name field.
	sysdeptDescName := sysdeptFields[0].Descriptor()
	// sysdept.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysdept.NameValidator = func() func(string) error {
		validators := sysdeptDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdeptDescLeaderID is the schema descriptor for leader_id field.
	sysdeptDescLeaderID := sysdeptFields[1].Descriptor()
	// sysdept.DefaultLeaderID holds the default value on creation for the leader_id field.
	sysdept.DefaultLeaderID = sysdeptDescLeaderID.Default.(int64)
	// sysdept.LeaderIDValidator is a validator for the "leader_id" field. It is called by the builders before save.
	sysdept.LeaderIDValidator = sysdeptDescLeaderID.Validators[0].(func(int64) error)
	// sysdeptDescMobile is the schema descriptor for mobile field.
	sysdeptDescMobile := sysdeptFields[2].Descriptor()
	// sysdept.DefaultMobile holds the default value on creation for the mobile field.
	sysdept.DefaultMobile = sysdeptDescMobile.Default.(string)
	// sysdeptDescEmail is the schema descriptor for email field.
	sysdeptDescEmail := sysdeptFields[3].Descriptor()
	// sysdept.DefaultEmail holds the default value on creation for the email field.
	sysdept.DefaultEmail = sysdeptDescEmail.Default.(string)
	// sysdeptDescParentID is the schema descriptor for parent_id field.
	sysdeptDescParentID := sysdeptFields[4].Descriptor()
	// sysdept.DefaultParentID holds the default value on creation for the parent_id field.
	sysdept.DefaultParentID = sysdeptDescParentID.Default.(int64)
	// sysdept.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	sysdept.ParentIDValidator = sysdeptDescParentID.Validators[0].(func(int64) error)
	// sysdeptDescID is the schema descriptor for id field.
	sysdeptDescID := sysdeptMixinFields0[0].Descriptor()
	// sysdept.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysdept.IDValidator = sysdeptDescID.Validators[0].(func(int64) error)
	sysdictMixin := schema.SysDict{}.Mixin()
	sysdictMixinFields0 := sysdictMixin[0].Fields()
	_ = sysdictMixinFields0
	sysdictMixinFields1 := sysdictMixin[1].Fields()
	_ = sysdictMixinFields1
	sysdictMixinFields2 := sysdictMixin[2].Fields()
	_ = sysdictMixinFields2
	sysdictMixinFields3 := sysdictMixin[3].Fields()
	_ = sysdictMixinFields3
	sysdictMixinFields4 := sysdictMixin[4].Fields()
	_ = sysdictMixinFields4
	sysdictMixinFields5 := sysdictMixin[5].Fields()
	_ = sysdictMixinFields5
	sysdictMixinFields6 := sysdictMixin[6].Fields()
	_ = sysdictMixinFields6
	sysdictFields := schema.SysDict{}.Fields()
	_ = sysdictFields
	// sysdictDescTenantID is the schema descriptor for tenant_id field.
	sysdictDescTenantID := sysdictMixinFields1[0].Descriptor()
	// sysdict.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	sysdict.TenantIDValidator = sysdictDescTenantID.Validators[0].(func(int64) error)
	// sysdictDescCreatedAt is the schema descriptor for created_at field.
	sysdictDescCreatedAt := sysdictMixinFields2[0].Descriptor()
	// sysdict.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysdict.DefaultCreatedAt = sysdictDescCreatedAt.Default.(func() time.Time)
	// sysdictDescCreatedID is the schema descriptor for created_id field.
	sysdictDescCreatedID := sysdictMixinFields2[1].Descriptor()
	// sysdict.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysdict.CreatedIDValidator = sysdictDescCreatedID.Validators[0].(func(int64) error)
	// sysdictDescCreatedBy is the schema descriptor for created_by field.
	sysdictDescCreatedBy := sysdictMixinFields2[2].Descriptor()
	// sysdict.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysdict.CreatedByValidator = func() func(string) error {
		validators := sysdictDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictDescUpdatedAt is the schema descriptor for updated_at field.
	sysdictDescUpdatedAt := sysdictMixinFields3[0].Descriptor()
	// sysdict.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysdict.DefaultUpdatedAt = sysdictDescUpdatedAt.Default.(func() time.Time)
	// sysdictDescUpdatedID is the schema descriptor for updated_id field.
	sysdictDescUpdatedID := sysdictMixinFields3[1].Descriptor()
	// sysdict.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysdict.UpdatedIDValidator = sysdictDescUpdatedID.Validators[0].(func(int64) error)
	// sysdictDescUpdatedBy is the schema descriptor for updated_by field.
	sysdictDescUpdatedBy := sysdictMixinFields3[2].Descriptor()
	// sysdict.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysdict.UpdatedByValidator = func() func(string) error {
		validators := sysdictDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictDescDeletedBy is the schema descriptor for deleted_by field.
	sysdictDescDeletedBy := sysdictMixinFields4[2].Descriptor()
	// sysdict.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	sysdict.DeletedByValidator = sysdictDescDeletedBy.Validators[0].(func(string) error)
	// sysdictDescRemark is the schema descriptor for remark field.
	sysdictDescRemark := sysdictMixinFields6[0].Descriptor()
	// sysdict.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysdict.RemarkValidator = sysdictDescRemark.Validators[0].(func(string) error)
	// sysdictDescName is the schema descriptor for name field.
	sysdictDescName := sysdictFields[0].Descriptor()
	// sysdict.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysdict.NameValidator = func() func(string) error {
		validators := sysdictDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictDescKey is the schema descriptor for key field.
	sysdictDescKey := sysdictFields[1].Descriptor()
	// sysdict.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	sysdict.KeyValidator = func() func(string) error {
		validators := sysdictDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictDescIsPublic is the schema descriptor for is_public field.
	sysdictDescIsPublic := sysdictFields[2].Descriptor()
	// sysdict.DefaultIsPublic holds the default value on creation for the is_public field.
	sysdict.DefaultIsPublic = sysdictDescIsPublic.Default.(bool)
	// sysdictDescID is the schema descriptor for id field.
	sysdictDescID := sysdictMixinFields0[0].Descriptor()
	// sysdict.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysdict.IDValidator = sysdictDescID.Validators[0].(func(int64) error)
	sysdictdataMixin := schema.SysDictData{}.Mixin()
	sysdictdataMixinFields0 := sysdictdataMixin[0].Fields()
	_ = sysdictdataMixinFields0
	sysdictdataMixinFields1 := sysdictdataMixin[1].Fields()
	_ = sysdictdataMixinFields1
	sysdictdataMixinFields2 := sysdictdataMixin[2].Fields()
	_ = sysdictdataMixinFields2
	sysdictdataMixinFields3 := sysdictdataMixin[3].Fields()
	_ = sysdictdataMixinFields3
	sysdictdataMixinFields4 := sysdictdataMixin[4].Fields()
	_ = sysdictdataMixinFields4
	sysdictdataMixinFields5 := sysdictdataMixin[5].Fields()
	_ = sysdictdataMixinFields5
	sysdictdataMixinFields6 := sysdictdataMixin[6].Fields()
	_ = sysdictdataMixinFields6
	sysdictdataFields := schema.SysDictData{}.Fields()
	_ = sysdictdataFields
	// sysdictdataDescTenantID is the schema descriptor for tenant_id field.
	sysdictdataDescTenantID := sysdictdataMixinFields1[0].Descriptor()
	// sysdictdata.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	sysdictdata.TenantIDValidator = sysdictdataDescTenantID.Validators[0].(func(int64) error)
	// sysdictdataDescCreatedAt is the schema descriptor for created_at field.
	sysdictdataDescCreatedAt := sysdictdataMixinFields2[0].Descriptor()
	// sysdictdata.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysdictdata.DefaultCreatedAt = sysdictdataDescCreatedAt.Default.(func() time.Time)
	// sysdictdataDescCreatedID is the schema descriptor for created_id field.
	sysdictdataDescCreatedID := sysdictdataMixinFields2[1].Descriptor()
	// sysdictdata.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysdictdata.CreatedIDValidator = sysdictdataDescCreatedID.Validators[0].(func(int64) error)
	// sysdictdataDescCreatedBy is the schema descriptor for created_by field.
	sysdictdataDescCreatedBy := sysdictdataMixinFields2[2].Descriptor()
	// sysdictdata.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysdictdata.CreatedByValidator = func() func(string) error {
		validators := sysdictdataDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictdataDescUpdatedAt is the schema descriptor for updated_at field.
	sysdictdataDescUpdatedAt := sysdictdataMixinFields3[0].Descriptor()
	// sysdictdata.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysdictdata.DefaultUpdatedAt = sysdictdataDescUpdatedAt.Default.(func() time.Time)
	// sysdictdataDescUpdatedID is the schema descriptor for updated_id field.
	sysdictdataDescUpdatedID := sysdictdataMixinFields3[1].Descriptor()
	// sysdictdata.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysdictdata.UpdatedIDValidator = sysdictdataDescUpdatedID.Validators[0].(func(int64) error)
	// sysdictdataDescUpdatedBy is the schema descriptor for updated_by field.
	sysdictdataDescUpdatedBy := sysdictdataMixinFields3[2].Descriptor()
	// sysdictdata.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysdictdata.UpdatedByValidator = func() func(string) error {
		validators := sysdictdataDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictdataDescDeletedBy is the schema descriptor for deleted_by field.
	sysdictdataDescDeletedBy := sysdictdataMixinFields4[2].Descriptor()
	// sysdictdata.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	sysdictdata.DeletedByValidator = sysdictdataDescDeletedBy.Validators[0].(func(string) error)
	// sysdictdataDescRemark is the schema descriptor for remark field.
	sysdictdataDescRemark := sysdictdataMixinFields6[0].Descriptor()
	// sysdictdata.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysdictdata.RemarkValidator = sysdictdataDescRemark.Validators[0].(func(string) error)
	// sysdictdataDescName is the schema descriptor for name field.
	sysdictdataDescName := sysdictdataFields[0].Descriptor()
	// sysdictdata.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysdictdata.NameValidator = func() func(string) error {
		validators := sysdictdataDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictdataDescKey is the schema descriptor for key field.
	sysdictdataDescKey := sysdictdataFields[1].Descriptor()
	// sysdictdata.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	sysdictdata.KeyValidator = func() func(string) error {
		validators := sysdictdataDescKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(key string) error {
			for _, fn := range fns {
				if err := fn(key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictdataDescValue is the schema descriptor for value field.
	sysdictdataDescValue := sysdictdataFields[2].Descriptor()
	// sysdictdata.ValueValidator is a validator for the "value" field. It is called by the builders before save.
	sysdictdata.ValueValidator = func() func(string) error {
		validators := sysdictdataDescValue.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(value string) error {
			for _, fn := range fns {
				if err := fn(value); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysdictdataDescDictID is the schema descriptor for dict_id field.
	sysdictdataDescDictID := sysdictdataFields[3].Descriptor()
	// sysdictdata.DefaultDictID holds the default value on creation for the dict_id field.
	sysdictdata.DefaultDictID = sysdictdataDescDictID.Default.(int64)
	// sysdictdata.DictIDValidator is a validator for the "dict_id" field. It is called by the builders before save.
	sysdictdata.DictIDValidator = sysdictdataDescDictID.Validators[0].(func(int64) error)
	// sysdictdataDescID is the schema descriptor for id field.
	sysdictdataDescID := sysdictdataMixinFields0[0].Descriptor()
	// sysdictdata.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysdictdata.IDValidator = sysdictdataDescID.Validators[0].(func(int64) error)
	sysmenuMixin := schema.SysMenu{}.Mixin()
	sysmenuMixinFields0 := sysmenuMixin[0].Fields()
	_ = sysmenuMixinFields0
	sysmenuMixinFields1 := sysmenuMixin[1].Fields()
	_ = sysmenuMixinFields1
	sysmenuMixinFields2 := sysmenuMixin[2].Fields()
	_ = sysmenuMixinFields2
	sysmenuMixinFields3 := sysmenuMixin[3].Fields()
	_ = sysmenuMixinFields3
	sysmenuMixinFields4 := sysmenuMixin[4].Fields()
	_ = sysmenuMixinFields4
	sysmenuMixinFields5 := sysmenuMixin[5].Fields()
	_ = sysmenuMixinFields5
	sysmenuMixinFields6 := sysmenuMixin[6].Fields()
	_ = sysmenuMixinFields6
	sysmenuFields := schema.SysMenu{}.Fields()
	_ = sysmenuFields
	// sysmenuDescCreatedAt is the schema descriptor for created_at field.
	sysmenuDescCreatedAt := sysmenuMixinFields1[0].Descriptor()
	// sysmenu.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysmenu.DefaultCreatedAt = sysmenuDescCreatedAt.Default.(func() time.Time)
	// sysmenuDescCreatedID is the schema descriptor for created_id field.
	sysmenuDescCreatedID := sysmenuMixinFields1[1].Descriptor()
	// sysmenu.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysmenu.CreatedIDValidator = sysmenuDescCreatedID.Validators[0].(func(int64) error)
	// sysmenuDescCreatedBy is the schema descriptor for created_by field.
	sysmenuDescCreatedBy := sysmenuMixinFields1[2].Descriptor()
	// sysmenu.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysmenu.CreatedByValidator = func() func(string) error {
		validators := sysmenuDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysmenuDescUpdatedAt is the schema descriptor for updated_at field.
	sysmenuDescUpdatedAt := sysmenuMixinFields2[0].Descriptor()
	// sysmenu.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysmenu.DefaultUpdatedAt = sysmenuDescUpdatedAt.Default.(func() time.Time)
	// sysmenuDescUpdatedID is the schema descriptor for updated_id field.
	sysmenuDescUpdatedID := sysmenuMixinFields2[1].Descriptor()
	// sysmenu.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysmenu.UpdatedIDValidator = sysmenuDescUpdatedID.Validators[0].(func(int64) error)
	// sysmenuDescUpdatedBy is the schema descriptor for updated_by field.
	sysmenuDescUpdatedBy := sysmenuMixinFields2[2].Descriptor()
	// sysmenu.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysmenu.UpdatedByValidator = func() func(string) error {
		validators := sysmenuDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysmenuDescDeletedBy is the schema descriptor for deleted_by field.
	sysmenuDescDeletedBy := sysmenuMixinFields3[2].Descriptor()
	// sysmenu.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	sysmenu.DeletedByValidator = sysmenuDescDeletedBy.Validators[0].(func(string) error)
	// sysmenuDescRemark is the schema descriptor for remark field.
	sysmenuDescRemark := sysmenuMixinFields5[0].Descriptor()
	// sysmenu.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysmenu.RemarkValidator = sysmenuDescRemark.Validators[0].(func(string) error)
	// sysmenuDescSort is the schema descriptor for sort field.
	sysmenuDescSort := sysmenuMixinFields6[0].Descriptor()
	// sysmenu.DefaultSort holds the default value on creation for the sort field.
	sysmenu.DefaultSort = sysmenuDescSort.Default.(uint32)
	// sysmenu.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	sysmenu.SortValidator = sysmenuDescSort.Validators[0].(func(uint32) error)
	// sysmenuDescName is the schema descriptor for name field.
	sysmenuDescName := sysmenuFields[1].Descriptor()
	// sysmenu.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysmenu.NameValidator = func() func(string) error {
		validators := sysmenuDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysmenuDescParentID is the schema descriptor for parent_id field.
	sysmenuDescParentID := sysmenuFields[2].Descriptor()
	// sysmenu.DefaultParentID holds the default value on creation for the parent_id field.
	sysmenu.DefaultParentID = sysmenuDescParentID.Default.(int64)
	// sysmenu.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	sysmenu.ParentIDValidator = sysmenuDescParentID.Validators[0].(func(int64) error)
	// sysmenuDescComponent is the schema descriptor for component field.
	sysmenuDescComponent := sysmenuFields[3].Descriptor()
	// sysmenu.DefaultComponent holds the default value on creation for the component field.
	sysmenu.DefaultComponent = sysmenuDescComponent.Default.(string)
	// sysmenuDescPath is the schema descriptor for path field.
	sysmenuDescPath := sysmenuFields[4].Descriptor()
	// sysmenu.DefaultPath holds the default value on creation for the path field.
	sysmenu.DefaultPath = sysmenuDescPath.Default.(string)
	// sysmenuDescIsRedirect is the schema descriptor for is_redirect field.
	sysmenuDescIsRedirect := sysmenuFields[6].Descriptor()
	// sysmenu.DefaultIsRedirect holds the default value on creation for the is_redirect field.
	sysmenu.DefaultIsRedirect = sysmenuDescIsRedirect.Default.(bool)
	// sysmenuDescRedirect is the schema descriptor for redirect field.
	sysmenuDescRedirect := sysmenuFields[7].Descriptor()
	// sysmenu.DefaultRedirect holds the default value on creation for the redirect field.
	sysmenu.DefaultRedirect = sysmenuDescRedirect.Default.(string)
	// sysmenuDescID is the schema descriptor for id field.
	sysmenuDescID := sysmenuMixinFields0[0].Descriptor()
	// sysmenu.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysmenu.IDValidator = sysmenuDescID.Validators[0].(func(int64) error)
	sysroleMixin := schema.SysRole{}.Mixin()
	sysroleMixinFields0 := sysroleMixin[0].Fields()
	_ = sysroleMixinFields0
	sysroleMixinFields1 := sysroleMixin[1].Fields()
	_ = sysroleMixinFields1
	sysroleMixinFields2 := sysroleMixin[2].Fields()
	_ = sysroleMixinFields2
	sysroleMixinFields3 := sysroleMixin[3].Fields()
	_ = sysroleMixinFields3
	sysroleMixinFields4 := sysroleMixin[4].Fields()
	_ = sysroleMixinFields4
	sysroleMixinFields5 := sysroleMixin[5].Fields()
	_ = sysroleMixinFields5
	sysroleMixinFields6 := sysroleMixin[6].Fields()
	_ = sysroleMixinFields6
	sysroleFields := schema.SysRole{}.Fields()
	_ = sysroleFields
	// sysroleDescCreatedAt is the schema descriptor for created_at field.
	sysroleDescCreatedAt := sysroleMixinFields1[0].Descriptor()
	// sysrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysrole.DefaultCreatedAt = sysroleDescCreatedAt.Default.(func() time.Time)
	// sysroleDescCreatedID is the schema descriptor for created_id field.
	sysroleDescCreatedID := sysroleMixinFields1[1].Descriptor()
	// sysrole.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysrole.CreatedIDValidator = sysroleDescCreatedID.Validators[0].(func(int64) error)
	// sysroleDescCreatedBy is the schema descriptor for created_by field.
	sysroleDescCreatedBy := sysroleMixinFields1[2].Descriptor()
	// sysrole.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysrole.CreatedByValidator = func() func(string) error {
		validators := sysroleDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysroleDescUpdatedAt is the schema descriptor for updated_at field.
	sysroleDescUpdatedAt := sysroleMixinFields2[0].Descriptor()
	// sysrole.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysrole.DefaultUpdatedAt = sysroleDescUpdatedAt.Default.(func() time.Time)
	// sysroleDescUpdatedID is the schema descriptor for updated_id field.
	sysroleDescUpdatedID := sysroleMixinFields2[1].Descriptor()
	// sysrole.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysrole.UpdatedIDValidator = sysroleDescUpdatedID.Validators[0].(func(int64) error)
	// sysroleDescUpdatedBy is the schema descriptor for updated_by field.
	sysroleDescUpdatedBy := sysroleMixinFields2[2].Descriptor()
	// sysrole.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysrole.UpdatedByValidator = func() func(string) error {
		validators := sysroleDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysroleDescDeletedBy is the schema descriptor for deleted_by field.
	sysroleDescDeletedBy := sysroleMixinFields3[2].Descriptor()
	// sysrole.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	sysrole.DeletedByValidator = sysroleDescDeletedBy.Validators[0].(func(string) error)
	// sysroleDescSort is the schema descriptor for sort field.
	sysroleDescSort := sysroleMixinFields5[0].Descriptor()
	// sysrole.DefaultSort holds the default value on creation for the sort field.
	sysrole.DefaultSort = sysroleDescSort.Default.(uint32)
	// sysrole.SortValidator is a validator for the "sort" field. It is called by the builders before save.
	sysrole.SortValidator = sysroleDescSort.Validators[0].(func(uint32) error)
	// sysroleDescRemark is the schema descriptor for remark field.
	sysroleDescRemark := sysroleMixinFields6[0].Descriptor()
	// sysrole.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysrole.RemarkValidator = sysroleDescRemark.Validators[0].(func(string) error)
	// sysroleDescName is the schema descriptor for name field.
	sysroleDescName := sysroleFields[0].Descriptor()
	// sysrole.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysrole.NameValidator = func() func(string) error {
		validators := sysroleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysroleDescCode is the schema descriptor for code field.
	sysroleDescCode := sysroleFields[1].Descriptor()
	// sysrole.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	sysrole.CodeValidator = func() func(string) error {
		validators := sysroleDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysroleDescID is the schema descriptor for id field.
	sysroleDescID := sysroleMixinFields0[0].Descriptor()
	// sysrole.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysrole.IDValidator = sysroleDescID.Validators[0].(func(int64) error)
	systenantMixin := schema.SysTenant{}.Mixin()
	systenantMixinFields0 := systenantMixin[0].Fields()
	_ = systenantMixinFields0
	systenantMixinFields1 := systenantMixin[1].Fields()
	_ = systenantMixinFields1
	systenantMixinFields2 := systenantMixin[2].Fields()
	_ = systenantMixinFields2
	systenantMixinFields3 := systenantMixin[3].Fields()
	_ = systenantMixinFields3
	systenantMixinFields4 := systenantMixin[4].Fields()
	_ = systenantMixinFields4
	systenantMixinFields5 := systenantMixin[5].Fields()
	_ = systenantMixinFields5
	systenantFields := schema.SysTenant{}.Fields()
	_ = systenantFields
	// systenantDescCreatedAt is the schema descriptor for created_at field.
	systenantDescCreatedAt := systenantMixinFields1[0].Descriptor()
	// systenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	systenant.DefaultCreatedAt = systenantDescCreatedAt.Default.(func() time.Time)
	// systenantDescCreatedID is the schema descriptor for created_id field.
	systenantDescCreatedID := systenantMixinFields1[1].Descriptor()
	// systenant.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	systenant.CreatedIDValidator = systenantDescCreatedID.Validators[0].(func(int64) error)
	// systenantDescCreatedBy is the schema descriptor for created_by field.
	systenantDescCreatedBy := systenantMixinFields1[2].Descriptor()
	// systenant.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	systenant.CreatedByValidator = func() func(string) error {
		validators := systenantDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// systenantDescUpdatedAt is the schema descriptor for updated_at field.
	systenantDescUpdatedAt := systenantMixinFields2[0].Descriptor()
	// systenant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systenant.DefaultUpdatedAt = systenantDescUpdatedAt.Default.(func() time.Time)
	// systenantDescUpdatedID is the schema descriptor for updated_id field.
	systenantDescUpdatedID := systenantMixinFields2[1].Descriptor()
	// systenant.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	systenant.UpdatedIDValidator = systenantDescUpdatedID.Validators[0].(func(int64) error)
	// systenantDescUpdatedBy is the schema descriptor for updated_by field.
	systenantDescUpdatedBy := systenantMixinFields2[2].Descriptor()
	// systenant.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	systenant.UpdatedByValidator = func() func(string) error {
		validators := systenantDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// systenantDescDeletedBy is the schema descriptor for deleted_by field.
	systenantDescDeletedBy := systenantMixinFields3[2].Descriptor()
	// systenant.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	systenant.DeletedByValidator = systenantDescDeletedBy.Validators[0].(func(string) error)
	// systenantDescRemark is the schema descriptor for remark field.
	systenantDescRemark := systenantMixinFields5[0].Descriptor()
	// systenant.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	systenant.RemarkValidator = systenantDescRemark.Validators[0].(func(string) error)
	// systenantDescName is the schema descriptor for name field.
	systenantDescName := systenantFields[0].Descriptor()
	// systenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	systenant.NameValidator = func() func(string) error {
		validators := systenantDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// systenantDescCode is the schema descriptor for code field.
	systenantDescCode := systenantFields[1].Descriptor()
	// systenant.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	systenant.CodeValidator = func() func(string) error {
		validators := systenantDescCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(code string) error {
			for _, fn := range fns {
				if err := fn(code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// systenantDescAdminID is the schema descriptor for admin_id field.
	systenantDescAdminID := systenantFields[2].Descriptor()
	// systenant.AdminIDValidator is a validator for the "admin_id" field. It is called by the builders before save.
	systenant.AdminIDValidator = systenantDescAdminID.Validators[0].(func(int64) error)
	// systenantDescParentID is the schema descriptor for parent_id field.
	systenantDescParentID := systenantFields[3].Descriptor()
	// systenant.DefaultParentID holds the default value on creation for the parent_id field.
	systenant.DefaultParentID = systenantDescParentID.Default.(int64)
	// systenant.ParentIDValidator is a validator for the "parent_id" field. It is called by the builders before save.
	systenant.ParentIDValidator = systenantDescParentID.Validators[0].(func(int64) error)
	// systenantDescID is the schema descriptor for id field.
	systenantDescID := systenantMixinFields0[0].Descriptor()
	// systenant.IDValidator is a validator for the "id" field. It is called by the builders before save.
	systenant.IDValidator = systenantDescID.Validators[0].(func(int64) error)
	sysuserMixin := schema.SysUser{}.Mixin()
	sysuserMixinFields0 := sysuserMixin[0].Fields()
	_ = sysuserMixinFields0
	sysuserMixinFields1 := sysuserMixin[1].Fields()
	_ = sysuserMixinFields1
	sysuserMixinFields2 := sysuserMixin[2].Fields()
	_ = sysuserMixinFields2
	sysuserMixinFields3 := sysuserMixin[3].Fields()
	_ = sysuserMixinFields3
	sysuserMixinFields4 := sysuserMixin[4].Fields()
	_ = sysuserMixinFields4
	sysuserMixinFields5 := sysuserMixin[5].Fields()
	_ = sysuserMixinFields5
	sysuserMixinFields6 := sysuserMixin[6].Fields()
	_ = sysuserMixinFields6
	sysuserFields := schema.SysUser{}.Fields()
	_ = sysuserFields
	// sysuserDescTenantID is the schema descriptor for tenant_id field.
	sysuserDescTenantID := sysuserMixinFields1[0].Descriptor()
	// sysuser.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	sysuser.TenantIDValidator = sysuserDescTenantID.Validators[0].(func(int64) error)
	// sysuserDescCreatedAt is the schema descriptor for created_at field.
	sysuserDescCreatedAt := sysuserMixinFields2[0].Descriptor()
	// sysuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysuser.DefaultCreatedAt = sysuserDescCreatedAt.Default.(func() time.Time)
	// sysuserDescCreatedID is the schema descriptor for created_id field.
	sysuserDescCreatedID := sysuserMixinFields2[1].Descriptor()
	// sysuser.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysuser.CreatedIDValidator = sysuserDescCreatedID.Validators[0].(func(int64) error)
	// sysuserDescCreatedBy is the schema descriptor for created_by field.
	sysuserDescCreatedBy := sysuserMixinFields2[2].Descriptor()
	// sysuser.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysuser.CreatedByValidator = func() func(string) error {
		validators := sysuserDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescUpdatedAt is the schema descriptor for updated_at field.
	sysuserDescUpdatedAt := sysuserMixinFields3[0].Descriptor()
	// sysuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysuser.DefaultUpdatedAt = sysuserDescUpdatedAt.Default.(func() time.Time)
	// sysuserDescUpdatedID is the schema descriptor for updated_id field.
	sysuserDescUpdatedID := sysuserMixinFields3[1].Descriptor()
	// sysuser.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysuser.UpdatedIDValidator = sysuserDescUpdatedID.Validators[0].(func(int64) error)
	// sysuserDescUpdatedBy is the schema descriptor for updated_by field.
	sysuserDescUpdatedBy := sysuserMixinFields3[2].Descriptor()
	// sysuser.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysuser.UpdatedByValidator = func() func(string) error {
		validators := sysuserDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescDeletedBy is the schema descriptor for deleted_by field.
	sysuserDescDeletedBy := sysuserMixinFields4[2].Descriptor()
	// sysuser.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	sysuser.DeletedByValidator = sysuserDescDeletedBy.Validators[0].(func(string) error)
	// sysuserDescRemark is the schema descriptor for remark field.
	sysuserDescRemark := sysuserMixinFields6[0].Descriptor()
	// sysuser.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysuser.RemarkValidator = sysuserDescRemark.Validators[0].(func(string) error)
	// sysuserDescUsername is the schema descriptor for username field.
	sysuserDescUsername := sysuserFields[0].Descriptor()
	// sysuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	sysuser.UsernameValidator = func() func(string) error {
		validators := sysuserDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescPassword is the schema descriptor for password field.
	sysuserDescPassword := sysuserFields[1].Descriptor()
	// sysuser.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	sysuser.PasswordValidator = func() func(string) error {
		validators := sysuserDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysuserDescNickname is the schema descriptor for nickname field.
	sysuserDescNickname := sysuserFields[2].Descriptor()
	// sysuser.DefaultNickname holds the default value on creation for the nickname field.
	sysuser.DefaultNickname = sysuserDescNickname.Default.(string)
	// sysuser.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	sysuser.NicknameValidator = sysuserDescNickname.Validators[0].(func(string) error)
	// sysuserDescMobile is the schema descriptor for mobile field.
	sysuserDescMobile := sysuserFields[3].Descriptor()
	// sysuser.DefaultMobile holds the default value on creation for the mobile field.
	sysuser.DefaultMobile = sysuserDescMobile.Default.(string)
	// sysuser.MobileValidator is a validator for the "mobile" field. It is called by the builders before save.
	sysuser.MobileValidator = sysuserDescMobile.Validators[0].(func(string) error)
	// sysuserDescEmail is the schema descriptor for email field.
	sysuserDescEmail := sysuserFields[4].Descriptor()
	// sysuser.DefaultEmail holds the default value on creation for the email field.
	sysuser.DefaultEmail = sysuserDescEmail.Default.(string)
	// sysuser.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	sysuser.EmailValidator = sysuserDescEmail.Validators[0].(func(string) error)
	// sysuserDescAvatar is the schema descriptor for avatar field.
	sysuserDescAvatar := sysuserFields[5].Descriptor()
	// sysuser.DefaultAvatar holds the default value on creation for the avatar field.
	sysuser.DefaultAvatar = sysuserDescAvatar.Default.(string)
	// sysuserDescDeptID is the schema descriptor for dept_id field.
	sysuserDescDeptID := sysuserFields[6].Descriptor()
	// sysuser.DefaultDeptID holds the default value on creation for the dept_id field.
	sysuser.DefaultDeptID = sysuserDescDeptID.Default.(int64)
	// sysuser.DeptIDValidator is a validator for the "dept_id" field. It is called by the builders before save.
	sysuser.DeptIDValidator = sysuserDescDeptID.Validators[0].(func(int64) error)
	// sysuserDescID is the schema descriptor for id field.
	sysuserDescID := sysuserMixinFields0[0].Descriptor()
	// sysuser.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysuser.IDValidator = sysuserDescID.Validators[0].(func(int64) error)
}
