// Code generated by ent, DO NOT EDIT.

package ent

import _ "github.com/saas-zero/saas-zero-basedata/ent/runtime"

// The schema-stitching logic is generated in github.com/saas-zero/saas-zero-basedata/ent/runtime/runtime.go
