// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-basedata/ent/sysapi"
	"github.com/saas-zero/saas-zero-basedata/ent/syspackage"
)

// SysApiCreate is the builder for creating a SysApi entity.
type SysApiCreate struct {
	config
	mutation *SysApiMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysApiCreate) SetCreatedAt(v time.Time) *SysApiCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableCreatedAt(v *time.Time) *SysApiCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *SysApiCreate) SetCreatedID(v int64) *SysApiCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysApiCreate) SetCreatedBy(v string) *SysApiCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysApiCreate) SetUpdatedAt(v time.Time) *SysApiCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableUpdatedAt(v *time.Time) *SysApiCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedID sets the "updated_id" field.
func (_c *SysApiCreate) SetUpdatedID(v int64) *SysApiCreate {
	_c.mutation.SetUpdatedID(v)
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SysApiCreate) SetUpdatedBy(v string) *SysApiCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysApiCreate) SetDeletedAt(v time.Time) *SysApiCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableDeletedAt(v *time.Time) *SysApiCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedID sets the "deleted_id" field.
func (_c *SysApiCreate) SetDeletedID(v int64) *SysApiCreate {
	_c.mutation.SetDeletedID(v)
	return _c
}

// SetNillableDeletedID sets the "deleted_id" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableDeletedID(v *int64) *SysApiCreate {
	if v != nil {
		_c.SetDeletedID(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *SysApiCreate) SetDeletedBy(v string) *SysApiCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableDeletedBy(v *string) *SysApiCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SysApiCreate) SetStatus(v sysapi.Status) *SysApiCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableStatus(v *sysapi.Status) *SysApiCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *SysApiCreate) SetRemark(v string) *SysApiCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableRemark(v *string) *SysApiCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetAPIName sets the "api_name" field.
func (_c *SysApiCreate) SetAPIName(v string) *SysApiCreate {
	_c.mutation.SetAPIName(v)
	return _c
}

// SetNillableAPIName sets the "api_name" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableAPIName(v *string) *SysApiCreate {
	if v != nil {
		_c.SetAPIName(*v)
	}
	return _c
}

// SetAPIType sets the "api_type" field.
func (_c *SysApiCreate) SetAPIType(v sysapi.APIType) *SysApiCreate {
	_c.mutation.SetAPIType(v)
	return _c
}

// SetNillableAPIType sets the "api_type" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableAPIType(v *sysapi.APIType) *SysApiCreate {
	if v != nil {
		_c.SetAPIType(*v)
	}
	return _c
}

// SetAPIPath sets the "api_path" field.
func (_c *SysApiCreate) SetAPIPath(v string) *SysApiCreate {
	_c.mutation.SetAPIPath(v)
	return _c
}

// SetNillableAPIPath sets the "api_path" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableAPIPath(v *string) *SysApiCreate {
	if v != nil {
		_c.SetAPIPath(*v)
	}
	return _c
}

// SetAPIMethod sets the "api_method" field.
func (_c *SysApiCreate) SetAPIMethod(v sysapi.APIMethod) *SysApiCreate {
	_c.mutation.SetAPIMethod(v)
	return _c
}

// SetNillableAPIMethod sets the "api_method" field if the given value is not nil.
func (_c *SysApiCreate) SetNillableAPIMethod(v *sysapi.APIMethod) *SysApiCreate {
	if v != nil {
		_c.SetAPIMethod(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysApiCreate) SetID(v int64) *SysApiCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddPackageIDs adds the "packages" edge to the SysPackage entity by IDs.
func (_c *SysApiCreate) AddPackageIDs(ids ...int64) *SysApiCreate {
	_c.mutation.AddPackageIDs(ids...)
	return _c
}

// AddPackages adds the "packages" edges to the SysPackage entity.
func (_c *SysApiCreate) AddPackages(v ...*SysPackage) *SysApiCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPackageIDs(ids...)
}

// Mutation returns the SysApiMutation object of the builder.
func (_c *SysApiCreate) Mutation() *SysApiMutation {
	return _c.mutation
}

// Save creates the SysApi in the database.
func (_c *SysApiCreate) Save(ctx context.Context) (*SysApi, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysApiCreate) SaveX(ctx context.Context) *SysApi {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysApiCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysApiCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysApiCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sysapi.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysapi.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sysapi.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sysapi.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysapi.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sysapi.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sysapi.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.APIName(); !ok {
		v := sysapi.DefaultAPIName
		_c.mutation.SetAPIName(v)
	}
	if _, ok := _c.mutation.APIType(); !ok {
		v := sysapi.DefaultAPIType
		_c.mutation.SetAPIType(v)
	}
	if _, ok := _c.mutation.APIPath(); !ok {
		v := sysapi.DefaultAPIPath
		_c.mutation.SetAPIPath(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysApiCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysApi.created_at"`)}
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		return &ValidationError{Name: "created_id", err: errors.New(`ent: missing required field "SysApi.created_id"`)}
	}
	if v, ok := _c.mutation.CreatedID(); ok {
		if err := sysapi.CreatedIDValidator(v); err != nil {
			return &ValidationError{Name: "created_id", err: fmt.Errorf(`ent: validator failed for field "SysApi.created_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysApi.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := sysapi.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "SysApi.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysApi.updated_at"`)}
	}
	if _, ok := _c.mutation.UpdatedID(); !ok {
		return &ValidationError{Name: "updated_id", err: errors.New(`ent: missing required field "SysApi.updated_id"`)}
	}
	if v, ok := _c.mutation.UpdatedID(); ok {
		if err := sysapi.UpdatedIDValidator(v); err != nil {
			return &ValidationError{Name: "updated_id", err: fmt.Errorf(`ent: validator failed for field "SysApi.updated_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SysApi.updated_by"`)}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := sysapi.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysApi.updated_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeletedBy(); ok {
		if err := sysapi.DeletedByValidator(v); err != nil {
			return &ValidationError{Name: "deleted_by", err: fmt.Errorf(`ent: validator failed for field "SysApi.deleted_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysApi.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sysapi.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysApi.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := sysapi.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysApi.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIName(); !ok {
		return &ValidationError{Name: "api_name", err: errors.New(`ent: missing required field "SysApi.api_name"`)}
	}
	if v, ok := _c.mutation.APIName(); ok {
		if err := sysapi.APINameValidator(v); err != nil {
			return &ValidationError{Name: "api_name", err: fmt.Errorf(`ent: validator failed for field "SysApi.api_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIType(); !ok {
		return &ValidationError{Name: "api_type", err: errors.New(`ent: missing required field "SysApi.api_type"`)}
	}
	if v, ok := _c.mutation.APIType(); ok {
		if err := sysapi.APITypeValidator(v); err != nil {
			return &ValidationError{Name: "api_type", err: fmt.Errorf(`ent: validator failed for field "SysApi.api_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIPath(); !ok {
		return &ValidationError{Name: "api_path", err: errors.New(`ent: missing required field "SysApi.api_path"`)}
	}
	if v, ok := _c.mutation.APIPath(); ok {
		if err := sysapi.APIPathValidator(v); err != nil {
			return &ValidationError{Name: "api_path", err: fmt.Errorf(`ent: validator failed for field "SysApi.api_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.APIMethod(); ok {
		if err := sysapi.APIMethodValidator(v); err != nil {
			return &ValidationError{Name: "api_method", err: fmt.Errorf(`ent: validator failed for field "SysApi.api_method": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysapi.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysApi.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SysApiCreate) sqlSave(ctx context.Context) (*SysApi, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysApiCreate) createSpec() (*SysApi, *sqlgraph.CreateSpec) {
	var (
		_node = &SysApi{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysapi.Table, sqlgraph.NewFieldSpec(sysapi.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysapi.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(sysapi.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysapi.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysapi.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedID(); ok {
		_spec.SetField(sysapi.FieldUpdatedID, field.TypeInt64, value)
		_node.UpdatedID = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(sysapi.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysapi.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.DeletedID(); ok {
		_spec.SetField(sysapi.FieldDeletedID, field.TypeInt64, value)
		_node.DeletedID = value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(sysapi.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sysapi.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(sysapi.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.APIName(); ok {
		_spec.SetField(sysapi.FieldAPIName, field.TypeString, value)
		_node.APIName = value
	}
	if value, ok := _c.mutation.APIType(); ok {
		_spec.SetField(sysapi.FieldAPIType, field.TypeEnum, value)
		_node.APIType = value
	}
	if value, ok := _c.mutation.APIPath(); ok {
		_spec.SetField(sysapi.FieldAPIPath, field.TypeString, value)
		_node.APIPath = value
	}
	if value, ok := _c.mutation.APIMethod(); ok {
		_spec.SetField(sysapi.FieldAPIMethod, field.TypeEnum, value)
		_node.APIMethod = value
	}
	if nodes := _c.mutation.PackagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   sysapi.PackagesTable,
			Columns: sysapi.PackagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(syspackage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SysApiCreateBulk is the builder for creating many SysApi entities in bulk.
type SysApiCreateBulk struct {
	config
	err      error
	builders []*SysApiCreate
}

// Save creates the SysApi entities in the database.
func (_c *SysApiCreateBulk) Save(ctx context.Context) ([]*SysApi, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysApi, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysApiMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysApiCreateBulk) SaveX(ctx context.Context) []*SysApi {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysApiCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysApiCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
