// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/saas-zero/saas-zero-basedata/ent/sysdept"
	"github.com/saas-zero/saas-zero-basedata/ent/systenant"
	"github.com/saas-zero/saas-zero-basedata/ent/sysuser"
)

// Department Table | 部门表
type SysDept struct {
	config `json:"-"`
	// ID of the ent.
	// Primary Key | 主键ID，可自定义雪花ID
	ID int64 `json:"id,omitempty"`
	// 租户ID | Tenant ID
	TenantID int64 `json:"tenant_id,omitempty"`
	// Create Time | 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Creator ID | 创建人ID
	CreatedID int64 `json:"created_id,omitempty"`
	// Creator Name | 创建人名称
	CreatedBy string `json:"created_by,omitempty"`
	// updated Time | 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// updated ID | 更新人ID
	UpdatedID int64 `json:"updated_id,omitempty"`
	// updated Name | 更新人名称
	UpdatedBy string `json:"updated_by,omitempty"`
	// deleted Time | 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// deleted ID | 删除人ID，逻辑删除用
	DeletedID int64 `json:"deleted_id,omitempty"`
	// deleted Name | 删除人名称
	DeletedBy string `json:"deleted_by,omitempty"`
	// 状态：active-有效，inactive-无效，suspended-暂停
	Status sysdept.Status `json:"status,omitempty"`
	// Sort Number | 排序编号
	Sort uint32 `json:"sort,omitempty"`
	// 名称 | Name
	Name string `json:"name,omitempty"`
	// 负责人ID | Leader ID
	LeaderID int64 `json:"leader_id,omitempty"`
	// 部门电话 | Department Phone
	Mobile string `json:"mobile,omitempty"`
	// 部门邮箱 | Department Email
	Email string `json:"email,omitempty"`
	// 父级ID | Parent ID
	ParentID int64 `json:"parent_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysDeptQuery when eager-loading is set.
	Edges        SysDeptEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SysDeptEdges holds the relations/edges for other nodes in the graph.
type SysDeptEdges struct {
	// SysTenant holds the value of the sys_tenant edge.
	SysTenant *SysTenant `json:"sys_tenant,omitempty"`
	// Leader holds the value of the leader edge.
	Leader *SysUser `json:"leader,omitempty"`
	// SysUsers holds the value of the sys_users edge.
	SysUsers []*SysUser `json:"sys_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SysTenantOrErr returns the SysTenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysDeptEdges) SysTenantOrErr() (*SysTenant, error) {
	if e.SysTenant != nil {
		return e.SysTenant, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: systenant.Label}
	}
	return nil, &NotLoadedError{edge: "sys_tenant"}
}

// LeaderOrErr returns the Leader value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SysDeptEdges) LeaderOrErr() (*SysUser, error) {
	if e.Leader != nil {
		return e.Leader, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: sysuser.Label}
	}
	return nil, &NotLoadedError{edge: "leader"}
}

// SysUsersOrErr returns the SysUsers value or an error if the edge
// was not loaded in eager-loading.
func (e SysDeptEdges) SysUsersOrErr() ([]*SysUser, error) {
	if e.loadedTypes[2] {
		return e.SysUsers, nil
	}
	return nil, &NotLoadedError{edge: "sys_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysDept) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysdept.FieldID, sysdept.FieldTenantID, sysdept.FieldCreatedID, sysdept.FieldUpdatedID, sysdept.FieldDeletedID, sysdept.FieldSort, sysdept.FieldLeaderID, sysdept.FieldParentID:
			values[i] = new(sql.NullInt64)
		case sysdept.FieldCreatedBy, sysdept.FieldUpdatedBy, sysdept.FieldDeletedBy, sysdept.FieldStatus, sysdept.FieldName, sysdept.FieldMobile, sysdept.FieldEmail:
			values[i] = new(sql.NullString)
		case sysdept.FieldCreatedAt, sysdept.FieldUpdatedAt, sysdept.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysDept fields.
func (_m *SysDept) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysdept.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sysdept.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.Int64
			}
		case sysdept.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysdept.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				_m.CreatedID = value.Int64
			}
		case sysdept.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case sysdept.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysdept.FieldUpdatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_id", values[i])
			} else if value.Valid {
				_m.UpdatedID = value.Int64
			}
		case sysdept.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case sysdept.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case sysdept.FieldDeletedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_id", values[i])
			} else if value.Valid {
				_m.DeletedID = value.Int64
			}
		case sysdept.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = value.String
			}
		case sysdept.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sysdept.Status(value.String)
			}
		case sysdept.FieldSort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort", values[i])
			} else if value.Valid {
				_m.Sort = uint32(value.Int64)
			}
		case sysdept.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sysdept.FieldLeaderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field leader_id", values[i])
			} else if value.Valid {
				_m.LeaderID = value.Int64
			}
		case sysdept.FieldMobile:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mobile", values[i])
			} else if value.Valid {
				_m.Mobile = value.String
			}
		case sysdept.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case sysdept.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysDept.
// This includes values selected through modifiers, order, etc.
func (_m *SysDept) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySysTenant queries the "sys_tenant" edge of the SysDept entity.
func (_m *SysDept) QuerySysTenant() *SysTenantQuery {
	return NewSysDeptClient(_m.config).QuerySysTenant(_m)
}

// QueryLeader queries the "leader" edge of the SysDept entity.
func (_m *SysDept) QueryLeader() *SysUserQuery {
	return NewSysDeptClient(_m.config).QueryLeader(_m)
}

// QuerySysUsers queries the "sys_users" edge of the SysDept entity.
func (_m *SysDept) QuerySysUsers() *SysUserQuery {
	return NewSysDeptClient(_m.config).QuerySysUsers(_m)
}

// Update returns a builder for updating this SysDept.
// Note that you need to call SysDept.Unwrap() before calling this method if this SysDept
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysDept) Update() *SysDeptUpdateOne {
	return NewSysDeptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysDept entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysDept) Unwrap() *SysDept {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysDept is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysDept) String() string {
	var builder strings.Builder
	builder.WriteString("SysDept(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedID))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedID))
	builder.WriteString(", ")
	builder.WriteString("deleted_by=")
	builder.WriteString(_m.DeletedBy)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("sort=")
	builder.WriteString(fmt.Sprintf("%v", _m.Sort))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("leader_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LeaderID))
	builder.WriteString(", ")
	builder.WriteString("mobile=")
	builder.WriteString(_m.Mobile)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteByte(')')
	return builder.String()
}

// SysDepts is a parsable slice of SysDept.
type SysDepts []*SysDept
