// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"system-service/ent/predicate"
	"system-service/ent/sysdict"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SysDictUpdate is the builder for updating SysDict entities.
type SysDictUpdate struct {
	config
	hooks    []Hook
	mutation *SysDictMutation
}

// Where appends a list predicates to the SysDictUpdate builder.
func (_u *SysDictUpdate) Where(ps ...predicate.SysDict) *SysDictUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *SysDictUpdate) SetTenantID(v int64) *SysDictUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableTenantID(v *int64) *SysDictUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *SysDictUpdate) AddTenantID(v int64) *SysDictUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysDictUpdate) SetUpdatedAt(v time.Time) *SysDictUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableUpdatedAt(v *time.Time) *SysDictUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedID sets the "updated_id" field.
func (_u *SysDictUpdate) SetUpdatedID(v int64) *SysDictUpdate {
	_u.mutation.ResetUpdatedID()
	_u.mutation.SetUpdatedID(v)
	return _u
}

// SetNillableUpdatedID sets the "updated_id" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableUpdatedID(v *int64) *SysDictUpdate {
	if v != nil {
		_u.SetUpdatedID(*v)
	}
	return _u
}

// AddUpdatedID adds value to the "updated_id" field.
func (_u *SysDictUpdate) AddUpdatedID(v int64) *SysDictUpdate {
	_u.mutation.AddUpdatedID(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysDictUpdate) SetUpdatedBy(v string) *SysDictUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableUpdatedBy(v *string) *SysDictUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysDictUpdate) SetDeletedAt(v time.Time) *SysDictUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableDeletedAt(v *time.Time) *SysDictUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysDictUpdate) ClearDeletedAt() *SysDictUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedID sets the "deleted_id" field.
func (_u *SysDictUpdate) SetDeletedID(v int64) *SysDictUpdate {
	_u.mutation.ResetDeletedID()
	_u.mutation.SetDeletedID(v)
	return _u
}

// SetNillableDeletedID sets the "deleted_id" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableDeletedID(v *int64) *SysDictUpdate {
	if v != nil {
		_u.SetDeletedID(*v)
	}
	return _u
}

// AddDeletedID adds value to the "deleted_id" field.
func (_u *SysDictUpdate) AddDeletedID(v int64) *SysDictUpdate {
	_u.mutation.AddDeletedID(v)
	return _u
}

// ClearDeletedID clears the value of the "deleted_id" field.
func (_u *SysDictUpdate) ClearDeletedID() *SysDictUpdate {
	_u.mutation.ClearDeletedID()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SysDictUpdate) SetDeletedBy(v string) *SysDictUpdate {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableDeletedBy(v *string) *SysDictUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SysDictUpdate) ClearDeletedBy() *SysDictUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysDictUpdate) SetStatus(v sysdict.Status) *SysDictUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableStatus(v *sysdict.Status) *SysDictUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SysDictUpdate) SetRemark(v string) *SysDictUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableRemark(v *string) *SysDictUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SysDictUpdate) ClearRemark() *SysDictUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetName sets the "name" field.
func (_u *SysDictUpdate) SetName(v string) *SysDictUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableName(v *string) *SysDictUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *SysDictUpdate) SetKey(v string) *SysDictUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableKey(v *string) *SysDictUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *SysDictUpdate) SetIsPublic(v bool) *SysDictUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *SysDictUpdate) SetNillableIsPublic(v *bool) *SysDictUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// Mutation returns the SysDictMutation object of the builder.
func (_u *SysDictUpdate) Mutation() *SysDictMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysDictUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysDictUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysDictUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysDictUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysDictUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := sysdict.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SysDict.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedID(); ok {
		if err := sysdict.UpdatedIDValidator(v); err != nil {
			return &ValidationError{Name: "updated_id", err: fmt.Errorf(`ent: validator failed for field "SysDict.updated_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := sysdict.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysDict.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedBy(); ok {
		if err := sysdict.DeletedByValidator(v); err != nil {
			return &ValidationError{Name: "deleted_by", err: fmt.Errorf(`ent: validator failed for field "SysDict.deleted_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sysdict.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysDict.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := sysdict.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysDict.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sysdict.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysDict.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := sysdict.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "SysDict.key": %w`, err)}
		}
	}
	return nil
}

func (_u *SysDictUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysdict.Table, sysdict.Columns, sqlgraph.NewFieldSpec(sysdict.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(sysdict.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(sysdict.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdict.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedID(); ok {
		_spec.SetField(sysdict.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedID(); ok {
		_spec.AddField(sysdict.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdict.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysdict.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysdict.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedID(); ok {
		_spec.SetField(sysdict.FieldDeletedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedID(); ok {
		_spec.AddField(sysdict.FieldDeletedID, field.TypeInt64, value)
	}
	if _u.mutation.DeletedIDCleared() {
		_spec.ClearField(sysdict.FieldDeletedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sysdict.FieldDeletedBy, field.TypeString, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sysdict.FieldDeletedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysdict.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(sysdict.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(sysdict.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysdict.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(sysdict.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(sysdict.FieldIsPublic, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysdict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysDictUpdateOne is the builder for updating a single SysDict entity.
type SysDictUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysDictMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *SysDictUpdateOne) SetTenantID(v int64) *SysDictUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableTenantID(v *int64) *SysDictUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *SysDictUpdateOne) AddTenantID(v int64) *SysDictUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysDictUpdateOne) SetUpdatedAt(v time.Time) *SysDictUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableUpdatedAt(v *time.Time) *SysDictUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedID sets the "updated_id" field.
func (_u *SysDictUpdateOne) SetUpdatedID(v int64) *SysDictUpdateOne {
	_u.mutation.ResetUpdatedID()
	_u.mutation.SetUpdatedID(v)
	return _u
}

// SetNillableUpdatedID sets the "updated_id" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableUpdatedID(v *int64) *SysDictUpdateOne {
	if v != nil {
		_u.SetUpdatedID(*v)
	}
	return _u
}

// AddUpdatedID adds value to the "updated_id" field.
func (_u *SysDictUpdateOne) AddUpdatedID(v int64) *SysDictUpdateOne {
	_u.mutation.AddUpdatedID(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysDictUpdateOne) SetUpdatedBy(v string) *SysDictUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableUpdatedBy(v *string) *SysDictUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysDictUpdateOne) SetDeletedAt(v time.Time) *SysDictUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableDeletedAt(v *time.Time) *SysDictUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysDictUpdateOne) ClearDeletedAt() *SysDictUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedID sets the "deleted_id" field.
func (_u *SysDictUpdateOne) SetDeletedID(v int64) *SysDictUpdateOne {
	_u.mutation.ResetDeletedID()
	_u.mutation.SetDeletedID(v)
	return _u
}

// SetNillableDeletedID sets the "deleted_id" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableDeletedID(v *int64) *SysDictUpdateOne {
	if v != nil {
		_u.SetDeletedID(*v)
	}
	return _u
}

// AddDeletedID adds value to the "deleted_id" field.
func (_u *SysDictUpdateOne) AddDeletedID(v int64) *SysDictUpdateOne {
	_u.mutation.AddDeletedID(v)
	return _u
}

// ClearDeletedID clears the value of the "deleted_id" field.
func (_u *SysDictUpdateOne) ClearDeletedID() *SysDictUpdateOne {
	_u.mutation.ClearDeletedID()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SysDictUpdateOne) SetDeletedBy(v string) *SysDictUpdateOne {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableDeletedBy(v *string) *SysDictUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SysDictUpdateOne) ClearDeletedBy() *SysDictUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysDictUpdateOne) SetStatus(v sysdict.Status) *SysDictUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableStatus(v *sysdict.Status) *SysDictUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SysDictUpdateOne) SetRemark(v string) *SysDictUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableRemark(v *string) *SysDictUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SysDictUpdateOne) ClearRemark() *SysDictUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetName sets the "name" field.
func (_u *SysDictUpdateOne) SetName(v string) *SysDictUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableName(v *string) *SysDictUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *SysDictUpdateOne) SetKey(v string) *SysDictUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableKey(v *string) *SysDictUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *SysDictUpdateOne) SetIsPublic(v bool) *SysDictUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *SysDictUpdateOne) SetNillableIsPublic(v *bool) *SysDictUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// Mutation returns the SysDictMutation object of the builder.
func (_u *SysDictUpdateOne) Mutation() *SysDictMutation {
	return _u.mutation
}

// Where appends a list predicates to the SysDictUpdate builder.
func (_u *SysDictUpdateOne) Where(ps ...predicate.SysDict) *SysDictUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysDictUpdateOne) Select(field string, fields ...string) *SysDictUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysDict entity.
func (_u *SysDictUpdateOne) Save(ctx context.Context) (*SysDict, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysDictUpdateOne) SaveX(ctx context.Context) *SysDict {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysDictUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysDictUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysDictUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := sysdict.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SysDict.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedID(); ok {
		if err := sysdict.UpdatedIDValidator(v); err != nil {
			return &ValidationError{Name: "updated_id", err: fmt.Errorf(`ent: validator failed for field "SysDict.updated_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := sysdict.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysDict.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedBy(); ok {
		if err := sysdict.DeletedByValidator(v); err != nil {
			return &ValidationError{Name: "deleted_by", err: fmt.Errorf(`ent: validator failed for field "SysDict.deleted_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sysdict.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysDict.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := sysdict.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysDict.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sysdict.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysDict.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Key(); ok {
		if err := sysdict.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "SysDict.key": %w`, err)}
		}
	}
	return nil
}

func (_u *SysDictUpdateOne) sqlSave(ctx context.Context) (_node *SysDict, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysdict.Table, sysdict.Columns, sqlgraph.NewFieldSpec(sysdict.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysDict.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysdict.FieldID)
		for _, f := range fields {
			if !sysdict.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysdict.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(sysdict.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(sysdict.FieldTenantID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysdict.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedID(); ok {
		_spec.SetField(sysdict.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedID(); ok {
		_spec.AddField(sysdict.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysdict.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysdict.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysdict.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedID(); ok {
		_spec.SetField(sysdict.FieldDeletedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedID(); ok {
		_spec.AddField(sysdict.FieldDeletedID, field.TypeInt64, value)
	}
	if _u.mutation.DeletedIDCleared() {
		_spec.ClearField(sysdict.FieldDeletedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sysdict.FieldDeletedBy, field.TypeString, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sysdict.FieldDeletedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysdict.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(sysdict.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(sysdict.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysdict.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(sysdict.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(sysdict.FieldIsPublic, field.TypeBool, value)
	}
	_node = &SysDict{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysdict.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
