// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"system-service/ent/sysdict"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// dict Table | 字典表
type SysDict struct {
	config `json:"-"`
	// ID of the ent.
	// Primary Key | 主键ID，可自定义雪花ID
	ID int64 `json:"id,omitempty"`
	// 租户ID，不能为空
	TenantID int64 `json:"tenant_id,omitempty"`
	// Create Time | 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Creator ID | 创建人ID
	CreatedID int64 `json:"created_id,omitempty"`
	// Creator Name | 创建人名称
	CreatedBy string `json:"created_by,omitempty"`
	// updated Time | 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// updated ID | 更新人ID
	UpdatedID int64 `json:"updated_id,omitempty"`
	// updated Name | 更新人名称
	UpdatedBy string `json:"updated_by,omitempty"`
	// deleted Time | 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// deleted ID | 删除人ID，逻辑删除用
	DeletedID int64 `json:"deleted_id,omitempty"`
	// deleted Name | 删除人名称
	DeletedBy string `json:"deleted_by,omitempty"`
	// 状态：active-有效，inactive-无效，suspended-暂停
	Status sysdict.Status `json:"status,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// 名称，不能为空
	Name string `json:"name,omitempty"`
	// key，不能为空
	Key string `json:"key,omitempty"`
	// Whether to be public for everyone | 是否公开词典，无需登录即可访问
	IsPublic     bool `json:"is_public,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysDict) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysdict.FieldIsPublic:
			values[i] = new(sql.NullBool)
		case sysdict.FieldID, sysdict.FieldTenantID, sysdict.FieldCreatedID, sysdict.FieldUpdatedID, sysdict.FieldDeletedID:
			values[i] = new(sql.NullInt64)
		case sysdict.FieldCreatedBy, sysdict.FieldUpdatedBy, sysdict.FieldDeletedBy, sysdict.FieldStatus, sysdict.FieldRemark, sysdict.FieldName, sysdict.FieldKey:
			values[i] = new(sql.NullString)
		case sysdict.FieldCreatedAt, sysdict.FieldUpdatedAt, sysdict.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysDict fields.
func (_m *SysDict) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysdict.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sysdict.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = value.Int64
			}
		case sysdict.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysdict.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				_m.CreatedID = value.Int64
			}
		case sysdict.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case sysdict.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysdict.FieldUpdatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_id", values[i])
			} else if value.Valid {
				_m.UpdatedID = value.Int64
			}
		case sysdict.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case sysdict.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case sysdict.FieldDeletedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_id", values[i])
			} else if value.Valid {
				_m.DeletedID = value.Int64
			}
		case sysdict.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = value.String
			}
		case sysdict.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sysdict.Status(value.String)
			}
		case sysdict.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case sysdict.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sysdict.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case sysdict.FieldIsPublic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_public", values[i])
			} else if value.Valid {
				_m.IsPublic = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysDict.
// This includes values selected through modifiers, order, etc.
func (_m *SysDict) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SysDict.
// Note that you need to call SysDict.Unwrap() before calling this method if this SysDict
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysDict) Update() *SysDictUpdateOne {
	return NewSysDictClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysDict entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysDict) Unwrap() *SysDict {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysDict is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysDict) String() string {
	var builder strings.Builder
	builder.WriteString("SysDict(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedID))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedID))
	builder.WriteString(", ")
	builder.WriteString("deleted_by=")
	builder.WriteString(_m.DeletedBy)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("is_public=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublic))
	builder.WriteByte(')')
	return builder.String()
}

// SysDicts is a parsable slice of SysDict.
type SysDicts []*SysDict
