// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-basedata/ent/predicate"
	"github.com/saas-zero/saas-zero-basedata/ent/sysoperationlog"
)

// SysOperationLogDelete is the builder for deleting a SysOperationLog entity.
type SysOperationLogDelete struct {
	config
	hooks    []Hook
	mutation *SysOperationLogMutation
}

// Where appends a list predicates to the SysOperationLogDelete builder.
func (_d *SysOperationLogDelete) Where(ps ...predicate.SysOperationLog) *SysOperationLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SysOperationLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SysOperationLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SysOperationLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sysoperationlog.Table, sqlgraph.NewFieldSpec(sysoperationlog.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SysOperationLogDeleteOne is the builder for deleting a single SysOperationLog entity.
type SysOperationLogDeleteOne struct {
	_d *SysOperationLogDelete
}

// Where appends a list predicates to the SysOperationLogDelete builder.
func (_d *SysOperationLogDeleteOne) Where(ps ...predicate.SysOperationLog) *SysOperationLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SysOperationLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sysoperationlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SysOperationLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
