// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-basedata/ent/predicate"
	"github.com/saas-zero/saas-zero-basedata/ent/sysapi"
	"github.com/saas-zero/saas-zero-basedata/ent/sysmenu"
	"github.com/saas-zero/saas-zero-basedata/ent/syspackage"
	"github.com/saas-zero/saas-zero-basedata/ent/systenant"
)

// SysPackageQuery is the builder for querying SysPackage entities.
type SysPackageQuery struct {
	config
	ctx         *QueryContext
	order       []syspackage.OrderOption
	inters      []Interceptor
	predicates  []predicate.SysPackage
	withMenus   *SysMenuQuery
	withApis    *SysApiQuery
	withTenants *SysTenantQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SysPackageQuery builder.
func (_q *SysPackageQuery) Where(ps ...predicate.SysPackage) *SysPackageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SysPackageQuery) Limit(limit int) *SysPackageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SysPackageQuery) Offset(offset int) *SysPackageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SysPackageQuery) Unique(unique bool) *SysPackageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SysPackageQuery) Order(o ...syspackage.OrderOption) *SysPackageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryMenus chains the current query on the "menus" edge.
func (_q *SysPackageQuery) QueryMenus() *SysMenuQuery {
	query := (&SysMenuClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(syspackage.Table, syspackage.FieldID, selector),
			sqlgraph.To(sysmenu.Table, sysmenu.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, syspackage.MenusTable, syspackage.MenusPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryApis chains the current query on the "apis" edge.
func (_q *SysPackageQuery) QueryApis() *SysApiQuery {
	query := (&SysApiClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(syspackage.Table, syspackage.FieldID, selector),
			sqlgraph.To(sysapi.Table, sysapi.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, syspackage.ApisTable, syspackage.ApisPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTenants chains the current query on the "tenants" edge.
func (_q *SysPackageQuery) QueryTenants() *SysTenantQuery {
	query := (&SysTenantClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(syspackage.Table, syspackage.FieldID, selector),
			sqlgraph.To(systenant.Table, systenant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, syspackage.TenantsTable, syspackage.TenantsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SysPackage entity from the query.
// Returns a *NotFoundError when no SysPackage was found.
func (_q *SysPackageQuery) First(ctx context.Context) (*SysPackage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{syspackage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SysPackageQuery) FirstX(ctx context.Context) *SysPackage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SysPackage ID from the query.
// Returns a *NotFoundError when no SysPackage ID was found.
func (_q *SysPackageQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{syspackage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SysPackageQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SysPackage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SysPackage entity is found.
// Returns a *NotFoundError when no SysPackage entities are found.
func (_q *SysPackageQuery) Only(ctx context.Context) (*SysPackage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{syspackage.Label}
	default:
		return nil, &NotSingularError{syspackage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SysPackageQuery) OnlyX(ctx context.Context) *SysPackage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SysPackage ID in the query.
// Returns a *NotSingularError when more than one SysPackage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SysPackageQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{syspackage.Label}
	default:
		err = &NotSingularError{syspackage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SysPackageQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SysPackages.
func (_q *SysPackageQuery) All(ctx context.Context) ([]*SysPackage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SysPackage, *SysPackageQuery]()
	return withInterceptors[[]*SysPackage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SysPackageQuery) AllX(ctx context.Context) []*SysPackage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SysPackage IDs.
func (_q *SysPackageQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(syspackage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SysPackageQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SysPackageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SysPackageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SysPackageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SysPackageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SysPackageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SysPackageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SysPackageQuery) Clone() *SysPackageQuery {
	if _q == nil {
		return nil
	}
	return &SysPackageQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]syspackage.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.SysPackage{}, _q.predicates...),
		withMenus:   _q.withMenus.Clone(),
		withApis:    _q.withApis.Clone(),
		withTenants: _q.withTenants.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithMenus tells the query-builder to eager-load the nodes that are connected to
// the "menus" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SysPackageQuery) WithMenus(opts ...func(*SysMenuQuery)) *SysPackageQuery {
	query := (&SysMenuClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMenus = query
	return _q
}

// WithApis tells the query-builder to eager-load the nodes that are connected to
// the "apis" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SysPackageQuery) WithApis(opts ...func(*SysApiQuery)) *SysPackageQuery {
	query := (&SysApiClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withApis = query
	return _q
}

// WithTenants tells the query-builder to eager-load the nodes that are connected to
// the "tenants" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SysPackageQuery) WithTenants(opts ...func(*SysTenantQuery)) *SysPackageQuery {
	query := (&SysTenantClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTenants = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SysPackage.Query().
//		GroupBy(syspackage.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SysPackageQuery) GroupBy(field string, fields ...string) *SysPackageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SysPackageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = syspackage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.SysPackage.Query().
//		Select(syspackage.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *SysPackageQuery) Select(fields ...string) *SysPackageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SysPackageSelect{SysPackageQuery: _q}
	sbuild.label = syspackage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SysPackageSelect configured with the given aggregations.
func (_q *SysPackageQuery) Aggregate(fns ...AggregateFunc) *SysPackageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SysPackageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !syspackage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SysPackageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SysPackage, error) {
	var (
		nodes       = []*SysPackage{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withMenus != nil,
			_q.withApis != nil,
			_q.withTenants != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SysPackage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SysPackage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withMenus; query != nil {
		if err := _q.loadMenus(ctx, query, nodes,
			func(n *SysPackage) { n.Edges.Menus = []*SysMenu{} },
			func(n *SysPackage, e *SysMenu) { n.Edges.Menus = append(n.Edges.Menus, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withApis; query != nil {
		if err := _q.loadApis(ctx, query, nodes,
			func(n *SysPackage) { n.Edges.Apis = []*SysApi{} },
			func(n *SysPackage, e *SysApi) { n.Edges.Apis = append(n.Edges.Apis, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTenants; query != nil {
		if err := _q.loadTenants(ctx, query, nodes,
			func(n *SysPackage) { n.Edges.Tenants = []*SysTenant{} },
			func(n *SysPackage, e *SysTenant) { n.Edges.Tenants = append(n.Edges.Tenants, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SysPackageQuery) loadMenus(ctx context.Context, query *SysMenuQuery, nodes []*SysPackage, init func(*SysPackage), assign func(*SysPackage, *SysMenu)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int64]*SysPackage)
	nids := make(map[int64]map[*SysPackage]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(syspackage.MenusTable)
		s.Join(joinT).On(s.C(sysmenu.FieldID), joinT.C(syspackage.MenusPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(syspackage.MenusPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(syspackage.MenusPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullInt64).Int64
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*SysPackage]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*SysMenu](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "menus" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *SysPackageQuery) loadApis(ctx context.Context, query *SysApiQuery, nodes []*SysPackage, init func(*SysPackage), assign func(*SysPackage, *SysApi)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int64]*SysPackage)
	nids := make(map[int64]map[*SysPackage]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(syspackage.ApisTable)
		s.Join(joinT).On(s.C(sysapi.FieldID), joinT.C(syspackage.ApisPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(syspackage.ApisPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(syspackage.ApisPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := values[0].(*sql.NullInt64).Int64
				inValue := values[1].(*sql.NullInt64).Int64
				if nids[inValue] == nil {
					nids[inValue] = map[*SysPackage]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*SysApi](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "apis" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *SysPackageQuery) loadTenants(ctx context.Context, query *SysTenantQuery, nodes []*SysPackage, init func(*SysPackage), assign func(*SysPackage, *SysTenant)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*SysPackage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(systenant.FieldPackageID)
	}
	query.Where(predicate.SysTenant(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(syspackage.TenantsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PackageID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "package_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SysPackageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SysPackageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(syspackage.Table, syspackage.Columns, sqlgraph.NewFieldSpec(syspackage.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syspackage.FieldID)
		for i := range fields {
			if fields[i] != syspackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SysPackageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(syspackage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = syspackage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SysPackageGroupBy is the group-by builder for SysPackage entities.
type SysPackageGroupBy struct {
	selector
	build *SysPackageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SysPackageGroupBy) Aggregate(fns ...AggregateFunc) *SysPackageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SysPackageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysPackageQuery, *SysPackageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SysPackageGroupBy) sqlScan(ctx context.Context, root *SysPackageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SysPackageSelect is the builder for selecting fields of SysPackage entities.
type SysPackageSelect struct {
	*SysPackageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SysPackageSelect) Aggregate(fns ...AggregateFunc) *SysPackageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SysPackageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SysPackageQuery, *SysPackageSelect](ctx, _s.SysPackageQuery, _s, _s.inters, v)
}

func (_s *SysPackageSelect) sqlScan(ctx context.Context, root *SysPackageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
