// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"system-service/ent/systenant"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// tenant Table | 租户表
type SysTenant struct {
	config `json:"-"`
	// ID of the ent.
	// Primary Key | 主键ID，可自定义雪花ID
	ID int64 `json:"id,omitempty"`
	// Create Time | 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Creator ID | 创建人ID
	CreatedID int64 `json:"created_id,omitempty"`
	// Creator Name | 创建人名称
	CreatedBy string `json:"created_by,omitempty"`
	// updated Time | 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// updated ID | 更新人ID
	UpdatedID int64 `json:"updated_id,omitempty"`
	// updated Name | 更新人名称
	UpdatedBy string `json:"updated_by,omitempty"`
	// deleted Time | 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// deleted ID | 删除人ID，逻辑删除用
	DeletedID int64 `json:"deleted_id,omitempty"`
	// deleted Name | 删除人名称
	DeletedBy string `json:"deleted_by,omitempty"`
	// 状态：active-有效，inactive-无效，suspended-暂停
	Status systenant.Status `json:"status,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// 名称，不能为空
	Name string `json:"name,omitempty"`
	// 编码，不能为空
	Code string `json:"code,omitempty"`
	// 管理员id，不能为空，创建租户的时候顺便创建用户
	AdminID int64 `json:"admin_id,omitempty"`
	// 父级id，不能为空,0为第一级
	ParentID int64 `json:"parent_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SysTenantQuery when eager-loading is set.
	Edges               SysTenantEdges `json:"edges"`
	sys_dept_sys_tenant *int64
	selectValues        sql.SelectValues
}

// SysTenantEdges holds the relations/edges for other nodes in the graph.
type SysTenantEdges struct {
	// Roles holds the value of the roles edge.
	Roles []*SysRole `json:"roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e SysTenantEdges) RolesOrErr() ([]*SysRole, error) {
	if e.loadedTypes[0] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysTenant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case systenant.FieldID, systenant.FieldCreatedID, systenant.FieldUpdatedID, systenant.FieldDeletedID, systenant.FieldAdminID, systenant.FieldParentID:
			values[i] = new(sql.NullInt64)
		case systenant.FieldCreatedBy, systenant.FieldUpdatedBy, systenant.FieldDeletedBy, systenant.FieldStatus, systenant.FieldRemark, systenant.FieldName, systenant.FieldCode:
			values[i] = new(sql.NullString)
		case systenant.FieldCreatedAt, systenant.FieldUpdatedAt, systenant.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case systenant.ForeignKeys[0]: // sys_dept_sys_tenant
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysTenant fields.
func (_m *SysTenant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case systenant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case systenant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case systenant.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				_m.CreatedID = value.Int64
			}
		case systenant.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case systenant.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case systenant.FieldUpdatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_id", values[i])
			} else if value.Valid {
				_m.UpdatedID = value.Int64
			}
		case systenant.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case systenant.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case systenant.FieldDeletedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_id", values[i])
			} else if value.Valid {
				_m.DeletedID = value.Int64
			}
		case systenant.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = value.String
			}
		case systenant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = systenant.Status(value.String)
			}
		case systenant.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case systenant.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case systenant.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case systenant.FieldAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = value.Int64
			}
		case systenant.FieldParentID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field parent_id", values[i])
			} else if value.Valid {
				_m.ParentID = value.Int64
			}
		case systenant.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field sys_dept_sys_tenant", value)
			} else if value.Valid {
				_m.sys_dept_sys_tenant = new(int64)
				*_m.sys_dept_sys_tenant = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysTenant.
// This includes values selected through modifiers, order, etc.
func (_m *SysTenant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRoles queries the "roles" edge of the SysTenant entity.
func (_m *SysTenant) QueryRoles() *SysRoleQuery {
	return NewSysTenantClient(_m.config).QueryRoles(_m)
}

// Update returns a builder for updating this SysTenant.
// Note that you need to call SysTenant.Unwrap() before calling this method if this SysTenant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysTenant) Update() *SysTenantUpdateOne {
	return NewSysTenantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysTenant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysTenant) Unwrap() *SysTenant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysTenant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysTenant) String() string {
	var builder strings.Builder
	builder.WriteString("SysTenant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedID))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedID))
	builder.WriteString(", ")
	builder.WriteString("deleted_by=")
	builder.WriteString(_m.DeletedBy)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("admin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdminID))
	builder.WriteString(", ")
	builder.WriteString("parent_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ParentID))
	builder.WriteByte(')')
	return builder.String()
}

// SysTenants is a parsable slice of SysTenant.
type SysTenants []*SysTenant
