// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-basedata/ent/sysdept"
	"github.com/saas-zero/saas-zero-basedata/ent/sysrole"
	"github.com/saas-zero/saas-zero-basedata/ent/systenant"
	"github.com/saas-zero/saas-zero-basedata/ent/sysuser"
)

// SysUserCreate is the builder for creating a SysUser entity.
type SysUserCreate struct {
	config
	mutation *SysUserMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (_c *SysUserCreate) SetTenantID(v int64) *SysUserCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysUserCreate) SetCreatedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableCreatedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *SysUserCreate) SetCreatedID(v int64) *SysUserCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysUserCreate) SetCreatedBy(v string) *SysUserCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysUserCreate) SetUpdatedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableUpdatedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedID sets the "updated_id" field.
func (_c *SysUserCreate) SetUpdatedID(v int64) *SysUserCreate {
	_c.mutation.SetUpdatedID(v)
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SysUserCreate) SetUpdatedBy(v string) *SysUserCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysUserCreate) SetDeletedAt(v time.Time) *SysUserCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableDeletedAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedID sets the "deleted_id" field.
func (_c *SysUserCreate) SetDeletedID(v int64) *SysUserCreate {
	_c.mutation.SetDeletedID(v)
	return _c
}

// SetNillableDeletedID sets the "deleted_id" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableDeletedID(v *int64) *SysUserCreate {
	if v != nil {
		_c.SetDeletedID(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *SysUserCreate) SetDeletedBy(v string) *SysUserCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableDeletedBy(v *string) *SysUserCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SysUserCreate) SetStatus(v sysuser.Status) *SysUserCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableStatus(v *sysuser.Status) *SysUserCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *SysUserCreate) SetRemark(v string) *SysUserCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableRemark(v *string) *SysUserCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *SysUserCreate) SetUsername(v string) *SysUserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *SysUserCreate) SetPassword(v string) *SysUserCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNickname sets the "nickname" field.
func (_c *SysUserCreate) SetNickname(v string) *SysUserCreate {
	_c.mutation.SetNickname(v)
	return _c
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableNickname(v *string) *SysUserCreate {
	if v != nil {
		_c.SetNickname(*v)
	}
	return _c
}

// SetMobile sets the "mobile" field.
func (_c *SysUserCreate) SetMobile(v string) *SysUserCreate {
	_c.mutation.SetMobile(v)
	return _c
}

// SetNillableMobile sets the "mobile" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableMobile(v *string) *SysUserCreate {
	if v != nil {
		_c.SetMobile(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *SysUserCreate) SetEmail(v string) *SysUserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableEmail(v *string) *SysUserCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetDeptID sets the "dept_id" field.
func (_c *SysUserCreate) SetDeptID(v int64) *SysUserCreate {
	_c.mutation.SetDeptID(v)
	return _c
}

// SetNillableDeptID sets the "dept_id" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableDeptID(v *int64) *SysUserCreate {
	if v != nil {
		_c.SetDeptID(*v)
	}
	return _c
}

// SetLoginIP sets the "login_ip" field.
func (_c *SysUserCreate) SetLoginIP(v string) *SysUserCreate {
	_c.mutation.SetLoginIP(v)
	return _c
}

// SetNillableLoginIP sets the "login_ip" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableLoginIP(v *string) *SysUserCreate {
	if v != nil {
		_c.SetLoginIP(*v)
	}
	return _c
}

// SetLoginAt sets the "login_at" field.
func (_c *SysUserCreate) SetLoginAt(v time.Time) *SysUserCreate {
	_c.mutation.SetLoginAt(v)
	return _c
}

// SetNillableLoginAt sets the "login_at" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableLoginAt(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetLoginAt(*v)
	}
	return _c
}

// SetLoginErrorCount sets the "login_error_count" field.
func (_c *SysUserCreate) SetLoginErrorCount(v int32) *SysUserCreate {
	_c.mutation.SetLoginErrorCount(v)
	return _c
}

// SetNillableLoginErrorCount sets the "login_error_count" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableLoginErrorCount(v *int32) *SysUserCreate {
	if v != nil {
		_c.SetLoginErrorCount(*v)
	}
	return _c
}

// SetLockoutUntil sets the "lockout_until" field.
func (_c *SysUserCreate) SetLockoutUntil(v time.Time) *SysUserCreate {
	_c.mutation.SetLockoutUntil(v)
	return _c
}

// SetNillableLockoutUntil sets the "lockout_until" field if the given value is not nil.
func (_c *SysUserCreate) SetNillableLockoutUntil(v *time.Time) *SysUserCreate {
	if v != nil {
		_c.SetLockoutUntil(*v)
	}
	return _c
}

// SetPosition sets the "position" field.
func (_c *SysUserCreate) SetPosition(v string) *SysUserCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *SysUserCreate) SetNillablePosition(v *string) *SysUserCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysUserCreate) SetID(v int64) *SysUserCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSysTenantID sets the "sys_tenant" edge to the SysTenant entity by ID.
func (_c *SysUserCreate) SetSysTenantID(id int64) *SysUserCreate {
	_c.mutation.SetSysTenantID(id)
	return _c
}

// SetSysTenant sets the "sys_tenant" edge to the SysTenant entity.
func (_c *SysUserCreate) SetSysTenant(v *SysTenant) *SysUserCreate {
	return _c.SetSysTenantID(v.ID)
}

// SetSysDeptID sets the "sys_dept" edge to the SysDept entity by ID.
func (_c *SysUserCreate) SetSysDeptID(id int64) *SysUserCreate {
	_c.mutation.SetSysDeptID(id)
	return _c
}

// SetNillableSysDeptID sets the "sys_dept" edge to the SysDept entity by ID if the given value is not nil.
func (_c *SysUserCreate) SetNillableSysDeptID(id *int64) *SysUserCreate {
	if id != nil {
		_c = _c.SetSysDeptID(*id)
	}
	return _c
}

// SetSysDept sets the "sys_dept" edge to the SysDept entity.
func (_c *SysUserCreate) SetSysDept(v *SysDept) *SysUserCreate {
	return _c.SetSysDeptID(v.ID)
}

// AddRoleIDs adds the "roles" edge to the SysRole entity by IDs.
func (_c *SysUserCreate) AddRoleIDs(ids ...int64) *SysUserCreate {
	_c.mutation.AddRoleIDs(ids...)
	return _c
}

// AddRoles adds the "roles" edges to the SysRole entity.
func (_c *SysUserCreate) AddRoles(v ...*SysRole) *SysUserCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRoleIDs(ids...)
}

// Mutation returns the SysUserMutation object of the builder.
func (_c *SysUserCreate) Mutation() *SysUserMutation {
	return _c.mutation
}

// Save creates the SysUser in the database.
func (_c *SysUserCreate) Save(ctx context.Context) (*SysUser, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysUserCreate) SaveX(ctx context.Context) *SysUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysUserCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sysuser.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysuser.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sysuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sysuser.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysuser.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sysuser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sysuser.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Nickname(); !ok {
		v := sysuser.DefaultNickname
		_c.mutation.SetNickname(v)
	}
	if _, ok := _c.mutation.Mobile(); !ok {
		v := sysuser.DefaultMobile
		_c.mutation.SetMobile(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := sysuser.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.DeptID(); !ok {
		v := sysuser.DefaultDeptID
		_c.mutation.SetDeptID(v)
	}
	if _, ok := _c.mutation.LoginIP(); !ok {
		v := sysuser.DefaultLoginIP
		_c.mutation.SetLoginIP(v)
	}
	if _, ok := _c.mutation.LoginErrorCount(); !ok {
		v := sysuser.DefaultLoginErrorCount
		_c.mutation.SetLoginErrorCount(v)
	}
	if _, ok := _c.mutation.Position(); !ok {
		v := sysuser.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysUserCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "SysUser.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := sysuser.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`ent: validator failed for field "SysUser.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysUser.created_at"`)}
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		return &ValidationError{Name: "created_id", err: errors.New(`ent: missing required field "SysUser.created_id"`)}
	}
	if v, ok := _c.mutation.CreatedID(); ok {
		if err := sysuser.CreatedIDValidator(v); err != nil {
			return &ValidationError{Name: "created_id", err: fmt.Errorf(`ent: validator failed for field "SysUser.created_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysUser.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := sysuser.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "SysUser.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysUser.updated_at"`)}
	}
	if _, ok := _c.mutation.UpdatedID(); !ok {
		return &ValidationError{Name: "updated_id", err: errors.New(`ent: missing required field "SysUser.updated_id"`)}
	}
	if v, ok := _c.mutation.UpdatedID(); ok {
		if err := sysuser.UpdatedIDValidator(v); err != nil {
			return &ValidationError{Name: "updated_id", err: fmt.Errorf(`ent: validator failed for field "SysUser.updated_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SysUser.updated_by"`)}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := sysuser.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysUser.updated_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeletedBy(); ok {
		if err := sysuser.DeletedByValidator(v); err != nil {
			return &ValidationError{Name: "deleted_by", err: fmt.Errorf(`ent: validator failed for field "SysUser.deleted_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysUser.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sysuser.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysUser.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := sysuser.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysUser.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "SysUser.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := sysuser.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "SysUser.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "SysUser.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := sysuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "SysUser.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Nickname(); !ok {
		return &ValidationError{Name: "nickname", err: errors.New(`ent: missing required field "SysUser.nickname"`)}
	}
	if v, ok := _c.mutation.Nickname(); ok {
		if err := sysuser.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "SysUser.nickname": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mobile(); !ok {
		return &ValidationError{Name: "mobile", err: errors.New(`ent: missing required field "SysUser.mobile"`)}
	}
	if v, ok := _c.mutation.Mobile(); ok {
		if err := sysuser.MobileValidator(v); err != nil {
			return &ValidationError{Name: "mobile", err: fmt.Errorf(`ent: validator failed for field "SysUser.mobile": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "SysUser.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := sysuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SysUser.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoginIP(); !ok {
		return &ValidationError{Name: "login_ip", err: errors.New(`ent: missing required field "SysUser.login_ip"`)}
	}
	if v, ok := _c.mutation.LoginIP(); ok {
		if err := sysuser.LoginIPValidator(v); err != nil {
			return &ValidationError{Name: "login_ip", err: fmt.Errorf(`ent: validator failed for field "SysUser.login_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LoginErrorCount(); !ok {
		return &ValidationError{Name: "login_error_count", err: errors.New(`ent: missing required field "SysUser.login_error_count"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "SysUser.position"`)}
	}
	if v, ok := _c.mutation.Position(); ok {
		if err := sysuser.PositionValidator(v); err != nil {
			return &ValidationError{Name: "position", err: fmt.Errorf(`ent: validator failed for field "SysUser.position": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysuser.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysUser.id": %w`, err)}
		}
	}
	if len(_c.mutation.SysTenantIDs()) == 0 {
		return &ValidationError{Name: "sys_tenant", err: errors.New(`ent: missing required edge "SysUser.sys_tenant"`)}
	}
	return nil
}

func (_c *SysUserCreate) sqlSave(ctx context.Context) (*SysUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysUserCreate) createSpec() (*SysUser, *sqlgraph.CreateSpec) {
	var (
		_node = &SysUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysuser.Table, sqlgraph.NewFieldSpec(sysuser.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(sysuser.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysuser.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedID(); ok {
		_spec.SetField(sysuser.FieldUpdatedID, field.TypeInt64, value)
		_node.UpdatedID = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(sysuser.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysuser.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.DeletedID(); ok {
		_spec.SetField(sysuser.FieldDeletedID, field.TypeInt64, value)
		_node.DeletedID = value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(sysuser.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sysuser.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(sysuser.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(sysuser.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(sysuser.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Nickname(); ok {
		_spec.SetField(sysuser.FieldNickname, field.TypeString, value)
		_node.Nickname = value
	}
	if value, ok := _c.mutation.Mobile(); ok {
		_spec.SetField(sysuser.FieldMobile, field.TypeString, value)
		_node.Mobile = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(sysuser.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.LoginIP(); ok {
		_spec.SetField(sysuser.FieldLoginIP, field.TypeString, value)
		_node.LoginIP = value
	}
	if value, ok := _c.mutation.LoginAt(); ok {
		_spec.SetField(sysuser.FieldLoginAt, field.TypeTime, value)
		_node.LoginAt = value
	}
	if value, ok := _c.mutation.LoginErrorCount(); ok {
		_spec.SetField(sysuser.FieldLoginErrorCount, field.TypeInt32, value)
		_node.LoginErrorCount = value
	}
	if value, ok := _c.mutation.LockoutUntil(); ok {
		_spec.SetField(sysuser.FieldLockoutUntil, field.TypeTime, value)
		_node.LockoutUntil = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(sysuser.FieldPosition, field.TypeString, value)
		_node.Position = value
	}
	if nodes := _c.mutation.SysTenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuser.SysTenantTable,
			Columns: []string{sysuser.SysTenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systenant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SysDeptIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sysuser.SysDeptTable,
			Columns: []string{sysuser.SysDeptColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysdept.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeptID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RolesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   sysuser.RolesTable,
			Columns: sysuser.RolesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sysrole.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SysUserCreateBulk is the builder for creating many SysUser entities in bulk.
type SysUserCreateBulk struct {
	config
	err      error
	builders []*SysUserCreate
}

// Save creates the SysUser entities in the database.
func (_c *SysUserCreateBulk) Save(ctx context.Context) ([]*SysUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysUserCreateBulk) SaveX(ctx context.Context) []*SysUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
