// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package server

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/logic/sysmenus"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/svc"
)

type SysMenusServer struct {
	svcCtx *svc.ServiceContext
	apps.UnimplementedSysMenusServer
}

func NewSysMenusServer(svcCtx *svc.ServiceContext) *SysMenusServer {
	return &SysMenusServer{
		svcCtx: svcCtx,
	}
}

func (s *SysMenusServer) CreateMenu(ctx context.Context, in *apps.MenuReq) (*apps.MenuResp, error) {
	l := sysmenuslogic.NewCreateMenuLogic(ctx, s.svcCtx)
	return l.CreateMenu(in)
}

func (s *SysMenusServer) UpdateMenu(ctx context.Context, in *apps.MenuReq) (*apps.MenuResp, error) {
	l := sysmenuslogic.NewUpdateMenuLogic(ctx, s.svcCtx)
	return l.UpdateMenu(in)
}

func (s *SysMenusServer) DeleteMenu(ctx context.Context, in *apps.IdsReq) (*apps.EmptyResp, error) {
	l := sysmenuslogic.NewDeleteMenuLogic(ctx, s.svcCtx)
	return l.DeleteMenu(in)
}

func (s *SysMenusServer) GetMenuList(ctx context.Context, in *apps.MenuPageReq) (*apps.MenuListResp, error) {
	l := sysmenuslogic.NewGetMenuListLogic(ctx, s.svcCtx)
	return l.GetMenuList(in)
}

func (s *SysMenusServer) GetMenuById(ctx context.Context, in *apps.IdReq) (*apps.MenuResp, error) {
	l := sysmenuslogic.NewGetMenuByIdLogic(ctx, s.svcCtx)
	return l.GetMenuById(in)
}

func (s *SysMenusServer) GetMenuTree(ctx context.Context, in *apps.EmptyReq) (*apps.MenuTreeResp, error) {
	l := sysmenuslogic.NewGetMenuTreeLogic(ctx, s.svcCtx)
	return l.GetMenuTree(in)
}

func (s *SysMenusServer) GetMenuRouters(ctx context.Context, in *apps.EmptyReq) (*apps.MenuTreeResp, error) {
	l := sysmenuslogic.NewGetMenuRoutersLogic(ctx, s.svcCtx)
	return l.GetMenuRouters(in)
}
