// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package server

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/logic/systenants"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/svc"
)

type SysTenantsServer struct {
	svcCtx *svc.ServiceContext
	apps.UnimplementedSysTenantsServer
}

func NewSysTenantsServer(svcCtx *svc.ServiceContext) *SysTenantsServer {
	return &SysTenantsServer{
		svcCtx: svcCtx,
	}
}

func (s *SysTenantsServer) CreateTenant(ctx context.Context, in *apps.TenantReq) (*apps.TenantResp, error) {
	l := systenantslogic.NewCreateTenantLogic(ctx, s.svcCtx)
	return l.CreateTenant(in)
}

func (s *SysTenantsServer) UpdateTenant(ctx context.Context, in *apps.TenantReq) (*apps.TenantResp, error) {
	l := systenantslogic.NewUpdateTenantLogic(ctx, s.svcCtx)
	return l.UpdateTenant(in)
}

func (s *SysTenantsServer) DeleteTenant(ctx context.Context, in *apps.IdsReq) (*apps.EmptyResp, error) {
	l := systenantslogic.NewDeleteTenantLogic(ctx, s.svcCtx)
	return l.DeleteTenant(in)
}

func (s *SysTenantsServer) GetTenantList(ctx context.Context, in *apps.TenantPageReq) (*apps.TenantListResp, error) {
	l := systenantslogic.NewGetTenantListLogic(ctx, s.svcCtx)
	return l.GetTenantList(in)
}

func (s *SysTenantsServer) GetTenantById(ctx context.Context, in *apps.IdReq) (*apps.TenantResp, error) {
	l := systenantslogic.NewGetTenantByIdLogic(ctx, s.svcCtx)
	return l.GetTenantById(in)
}

func (s *SysTenantsServer) ChangeTenantStatus(ctx context.Context, in *apps.TenantReq) (*apps.EmptyResp, error) {
	l := systenantslogic.NewChangeTenantStatusLogic(ctx, s.svcCtx)
	return l.ChangeTenantStatus(in)
}
