// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package sysmenus

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyReq     = apps.EmptyReq
	EmptyResp    = apps.EmptyResp
	IdReq        = apps.IdReq
	IdsReq       = apps.IdsReq
	MenuListResp = apps.MenuListResp
	MenuPageReq  = apps.MenuPageReq
	MenuReq      = apps.MenuReq
	MenuResp     = apps.MenuResp
	MenuTreeResp = apps.MenuTreeResp

	SysMenus interface {
		CreateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*MenuResp, error)
		UpdateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*MenuResp, error)
		DeleteMenu(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error)
		GetMenuList(ctx context.Context, in *MenuPageReq, opts ...grpc.CallOption) (*MenuListResp, error)
		GetMenuById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MenuResp, error)
		GetMenuTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error)
		GetMenuRouters(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error)
	}

	defaultSysMenus struct {
		cli zrpc.Client
	}
)

func NewSysMenus(cli zrpc.Client) SysMenus {
	return &defaultSysMenus{
		cli: cli,
	}
}

func (m *defaultSysMenus) CreateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*MenuResp, error) {
	client := apps.NewSysMenusClient(m.cli.Conn())
	return client.CreateMenu(ctx, in, opts...)
}

func (m *defaultSysMenus) UpdateMenu(ctx context.Context, in *MenuReq, opts ...grpc.CallOption) (*MenuResp, error) {
	client := apps.NewSysMenusClient(m.cli.Conn())
	return client.UpdateMenu(ctx, in, opts...)
}

func (m *defaultSysMenus) DeleteMenu(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	client := apps.NewSysMenusClient(m.cli.Conn())
	return client.DeleteMenu(ctx, in, opts...)
}

func (m *defaultSysMenus) GetMenuList(ctx context.Context, in *MenuPageReq, opts ...grpc.CallOption) (*MenuListResp, error) {
	client := apps.NewSysMenusClient(m.cli.Conn())
	return client.GetMenuList(ctx, in, opts...)
}

func (m *defaultSysMenus) GetMenuById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*MenuResp, error) {
	client := apps.NewSysMenusClient(m.cli.Conn())
	return client.GetMenuById(ctx, in, opts...)
}

func (m *defaultSysMenus) GetMenuTree(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error) {
	client := apps.NewSysMenusClient(m.cli.Conn())
	return client.GetMenuTree(ctx, in, opts...)
}

func (m *defaultSysMenus) GetMenuRouters(ctx context.Context, in *EmptyReq, opts ...grpc.CallOption) (*MenuTreeResp, error) {
	client := apps.NewSysMenusClient(m.cli.Conn())
	return client.GetMenuRouters(ctx, in, opts...)
}
