// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package server

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/logic/sysroles"
	"github.com/saas-zero/saas-zero-basedata/rpc/internal/svc"
)

type SysRolesServer struct {
	svcCtx *svc.ServiceContext
	apps.UnimplementedSysRolesServer
}

func NewSysRolesServer(svcCtx *svc.ServiceContext) *SysRolesServer {
	return &SysRolesServer{
		svcCtx: svcCtx,
	}
}

func (s *SysRolesServer) CreateRole(ctx context.Context, in *apps.RoleReq) (*apps.RoleResp, error) {
	l := sysroleslogic.NewCreateRoleLogic(ctx, s.svcCtx)
	return l.CreateRole(in)
}

func (s *SysRolesServer) UpdateRole(ctx context.Context, in *apps.RoleReq) (*apps.RoleResp, error) {
	l := sysroleslogic.NewUpdateRoleLogic(ctx, s.svcCtx)
	return l.UpdateRole(in)
}

func (s *SysRolesServer) DeleteRole(ctx context.Context, in *apps.IdsReq) (*apps.EmptyResp, error) {
	l := sysroleslogic.NewDeleteRoleLogic(ctx, s.svcCtx)
	return l.DeleteRole(in)
}

func (s *SysRolesServer) GetRoleList(ctx context.Context, in *apps.RolePageReq) (*apps.RoleListResp, error) {
	l := sysroleslogic.NewGetRoleListLogic(ctx, s.svcCtx)
	return l.GetRoleList(in)
}

func (s *SysRolesServer) GetRoleById(ctx context.Context, in *apps.IdReq) (*apps.RoleResp, error) {
	l := sysroleslogic.NewGetRoleByIdLogic(ctx, s.svcCtx)
	return l.GetRoleById(in)
}

func (s *SysRolesServer) AssignMenus(ctx context.Context, in *apps.RoleReq) (*apps.EmptyResp, error) {
	l := sysroleslogic.NewAssignMenusLogic(ctx, s.svcCtx)
	return l.AssignMenus(in)
}

func (s *SysRolesServer) AssignApis(ctx context.Context, in *apps.RoleReq) (*apps.EmptyResp, error) {
	l := sysroleslogic.NewAssignApisLogic(ctx, s.svcCtx)
	return l.AssignApis(in)
}
