// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: basedata_service.proto

package syslogs

import (
	"context"

	"github.com/saas-zero/saas-zero-basedata/rpc/apps"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LogPageReq           = apps.LogPageReq
	LoginLogListResp     = apps.LoginLogListResp
	OperationLogListResp = apps.OperationLogListResp

	SysLogs interface {
		GetLoginLogList(ctx context.Context, in *LogPageReq, opts ...grpc.CallOption) (*LoginLogListResp, error)
		GetOperationLogList(ctx context.Context, in *LogPageReq, opts ...grpc.CallOption) (*OperationLogListResp, error)
	}

	defaultSysLogs struct {
		cli zrpc.Client
	}
)

func NewSysLogs(cli zrpc.Client) SysLogs {
	return &defaultSysLogs{
		cli: cli,
	}
}

func (m *defaultSysLogs) GetLoginLogList(ctx context.Context, in *LogPageReq, opts ...grpc.CallOption) (*LoginLogListResp, error) {
	client := apps.NewSysLogsClient(m.cli.Conn())
	return client.GetLoginLogList(ctx, in, opts...)
}

func (m *defaultSysLogs) GetOperationLogList(ctx context.Context, in *LogPageReq, opts ...grpc.CallOption) (*OperationLogListResp, error) {
	client := apps.NewSysLogsClient(m.cli.Conn())
	return client.GetOperationLogList(ctx, in, opts...)
}
